package nodx_test

// Code generated by NodX. DO NOT EDIT.

import (
	"fmt"

	nodx "github.com/varavelio/nodxgo"
)

func ExampleA() {
	node := nodx.A(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <a id="1">Hello World!</a>
}

func ExampleAbbrEl() {
	node := nodx.AbbrEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <abbr id="1">Hello World!</abbr>
}

func ExampleAcronym() {
	node := nodx.Acronym(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <acronym id="1">Hello World!</acronym>
}

func ExampleAddress() {
	node := nodx.Address(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <address id="1">Hello World!</address>
}

func ExampleApplet() {
	node := nodx.Applet(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <applet id="1">Hello World!</applet>
}

func ExampleArea() {
	node := nodx.Area(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <area id="1">
}

func ExampleArticle() {
	node := nodx.Article(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <article id="1">Hello World!</article>
}

func ExampleAside() {
	node := nodx.Aside(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <aside id="1">Hello World!</aside>
}

func ExampleAudio() {
	node := nodx.Audio(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <audio id="1">Hello World!</audio>
}

func ExampleB() {
	node := nodx.B(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <b id="1">Hello World!</b>
}

func ExampleBase() {
	node := nodx.Base(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <base id="1">
}

func ExampleBasefont() {
	node := nodx.Basefont(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <basefont id="1">
}

func ExampleBdi() {
	node := nodx.Bdi(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <bdi id="1">Hello World!</bdi>
}

func ExampleBdo() {
	node := nodx.Bdo(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <bdo id="1">Hello World!</bdo>
}

func ExampleBgsound() {
	node := nodx.Bgsound(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <bgsound id="1">
}

func ExampleBig() {
	node := nodx.Big(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <big id="1">Hello World!</big>
}

func ExampleBlink() {
	node := nodx.Blink(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <blink id="1">Hello World!</blink>
}

func ExampleBlockquote() {
	node := nodx.Blockquote(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <blockquote id="1">Hello World!</blockquote>
}

func ExampleBody() {
	node := nodx.Body(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <body id="1">Hello World!</body>
}

func ExampleBr() {
	node := nodx.Br(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <br id="1">
}

func ExampleButton() {
	node := nodx.Button(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <button id="1">Hello World!</button>
}

func ExampleCanvas() {
	node := nodx.Canvas(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <canvas id="1">Hello World!</canvas>
}

func ExampleCaption() {
	node := nodx.Caption(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <caption id="1">Hello World!</caption>
}

func ExampleCenter() {
	node := nodx.Center(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <center id="1">Hello World!</center>
}

func ExampleCiteEl() {
	node := nodx.CiteEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <cite id="1">Hello World!</cite>
}

func ExampleCodeEl() {
	node := nodx.CodeEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <code id="1">Hello World!</code>
}

func ExampleCol() {
	node := nodx.Col(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <col id="1">
}

func ExampleColgroup() {
	node := nodx.Colgroup(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <colgroup id="1">Hello World!</colgroup>
}

func ExampleCommand() {
	node := nodx.Command(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <command id="1">
}

func ExampleContentEl() {
	node := nodx.ContentEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <content id="1">Hello World!</content>
}

func ExampleDataEl() {
	node := nodx.DataEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <data id="1">Hello World!</data>
}

func ExampleDatalist() {
	node := nodx.Datalist(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <datalist id="1">Hello World!</datalist>
}

func ExampleDd() {
	node := nodx.Dd(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <dd id="1">Hello World!</dd>
}

func ExampleDel() {
	node := nodx.Del(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <del id="1">Hello World!</del>
}

func ExampleDetails() {
	node := nodx.Details(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <details id="1">Hello World!</details>
}

func ExampleDfn() {
	node := nodx.Dfn(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <dfn id="1">Hello World!</dfn>
}

func ExampleDialog() {
	node := nodx.Dialog(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <dialog id="1">Hello World!</dialog>
}

func ExampleDirEl() {
	node := nodx.DirEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <dir id="1">Hello World!</dir>
}

func ExampleDiv() {
	node := nodx.Div(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <div id="1">Hello World!</div>
}

func ExampleDl() {
	node := nodx.Dl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <dl id="1">Hello World!</dl>
}

func ExampleDt() {
	node := nodx.Dt(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <dt id="1">Hello World!</dt>
}

func ExampleElement() {
	node := nodx.Element(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <element id="1">Hello World!</element>
}

func ExampleEm() {
	node := nodx.Em(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <em id="1">Hello World!</em>
}

func ExampleEmbed() {
	node := nodx.Embed(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <embed id="1">
}

func ExampleFieldset() {
	node := nodx.Fieldset(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <fieldset id="1">Hello World!</fieldset>
}

func ExampleFigcaption() {
	node := nodx.Figcaption(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <figcaption id="1">Hello World!</figcaption>
}

func ExampleFigure() {
	node := nodx.Figure(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <figure id="1">Hello World!</figure>
}

func ExampleFont() {
	node := nodx.Font(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <font id="1">Hello World!</font>
}

func ExampleFooter() {
	node := nodx.Footer(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <footer id="1">Hello World!</footer>
}

func ExampleFormEl() {
	node := nodx.FormEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <form id="1">Hello World!</form>
}

func ExampleFrameEl() {
	node := nodx.FrameEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <frame id="1">Hello World!</frame>
}

func ExampleFrameset() {
	node := nodx.Frameset(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <frameset id="1">Hello World!</frameset>
}

func ExampleH1() {
	node := nodx.H1(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <h1 id="1">Hello World!</h1>
}

func ExampleH2() {
	node := nodx.H2(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <h2 id="1">Hello World!</h2>
}

func ExampleH3() {
	node := nodx.H3(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <h3 id="1">Hello World!</h3>
}

func ExampleH4() {
	node := nodx.H4(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <h4 id="1">Hello World!</h4>
}

func ExampleH5() {
	node := nodx.H5(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <h5 id="1">Hello World!</h5>
}

func ExampleH6() {
	node := nodx.H6(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <h6 id="1">Hello World!</h6>
}

func ExampleHead() {
	node := nodx.Head(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <head id="1">Hello World!</head>
}

func ExampleHeader() {
	node := nodx.Header(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <header id="1">Hello World!</header>
}

func ExampleHgroup() {
	node := nodx.Hgroup(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <hgroup id="1">Hello World!</hgroup>
}

func ExampleHr() {
	node := nodx.Hr(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <hr id="1">
}

func ExampleHtml() {
	node := nodx.Html(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <html id="1">Hello World!</html>
}

func ExampleI() {
	node := nodx.I(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <i id="1">Hello World!</i>
}

func ExampleIframe() {
	node := nodx.Iframe(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <iframe id="1">Hello World!</iframe>
}

func ExampleImage() {
	node := nodx.Image(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <image id="1">
}

func ExampleImg() {
	node := nodx.Img(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <img id="1">
}

func ExampleInput() {
	node := nodx.Input(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <input id="1">
}

func ExampleIns() {
	node := nodx.Ins(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <ins id="1">Hello World!</ins>
}

func ExampleKbd() {
	node := nodx.Kbd(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <kbd id="1">Hello World!</kbd>
}

func ExampleKeygen() {
	node := nodx.Keygen(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <keygen id="1">
}

func ExampleLabelEl() {
	node := nodx.LabelEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <label id="1">Hello World!</label>
}

func ExampleLegend() {
	node := nodx.Legend(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <legend id="1">Hello World!</legend>
}

func ExampleLi() {
	node := nodx.Li(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <li id="1">Hello World!</li>
}

func ExampleLink() {
	node := nodx.Link(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <link id="1">
}

func ExampleMain() {
	node := nodx.Main(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <main id="1">Hello World!</main>
}

func ExampleMapEl() {
	node := nodx.MapEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <map id="1">Hello World!</map>
}

func ExampleMark() {
	node := nodx.Mark(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <mark id="1">Hello World!</mark>
}

func ExampleMarquee() {
	node := nodx.Marquee(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <marquee id="1">Hello World!</marquee>
}

func ExampleMenu() {
	node := nodx.Menu(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <menu id="1">Hello World!</menu>
}

func ExampleMenuitem() {
	node := nodx.Menuitem(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <menuitem id="1">
}

func ExampleMeta() {
	node := nodx.Meta(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <meta id="1">
}

func ExampleMeter() {
	node := nodx.Meter(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <meter id="1">Hello World!</meter>
}

func ExampleMulticol() {
	node := nodx.Multicol(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <multicol id="1">Hello World!</multicol>
}

func ExampleNav() {
	node := nodx.Nav(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <nav id="1">Hello World!</nav>
}

func ExampleNextid() {
	node := nodx.Nextid(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <nextid id="1">
}

func ExampleNobr() {
	node := nodx.Nobr(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <nobr id="1">Hello World!</nobr>
}

func ExampleNoembed() {
	node := nodx.Noembed(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <noembed id="1">Hello World!</noembed>
}

func ExampleNoframes() {
	node := nodx.Noframes(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <noframes id="1">Hello World!</noframes>
}

func ExampleNoscript() {
	node := nodx.Noscript(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <noscript id="1">Hello World!</noscript>
}

func ExampleObject() {
	node := nodx.Object(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <object id="1">Hello World!</object>
}

func ExampleOl() {
	node := nodx.Ol(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <ol id="1">Hello World!</ol>
}

func ExampleOptgroup() {
	node := nodx.Optgroup(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <optgroup id="1">Hello World!</optgroup>
}

func ExampleOption() {
	node := nodx.Option(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <option id="1">Hello World!</option>
}

func ExampleOutput() {
	node := nodx.Output(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <output id="1">Hello World!</output>
}

func ExampleP() {
	node := nodx.P(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <p id="1">Hello World!</p>
}

func ExampleParam() {
	node := nodx.Param(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <param id="1">
}

func ExamplePicture() {
	node := nodx.Picture(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <picture id="1">Hello World!</picture>
}

func ExamplePlaintext() {
	node := nodx.Plaintext(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <plaintext id="1">Hello World!</plaintext>
}

func ExamplePortal() {
	node := nodx.Portal(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <portal id="1">Hello World!</portal>
}

func ExamplePre() {
	node := nodx.Pre(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <pre id="1">Hello World!</pre>
}

func ExampleProgress() {
	node := nodx.Progress(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <progress id="1">Hello World!</progress>
}

func ExampleQ() {
	node := nodx.Q(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <q id="1">Hello World!</q>
}

func ExampleRb() {
	node := nodx.Rb(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <rb id="1">Hello World!</rb>
}

func ExampleRp() {
	node := nodx.Rp(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <rp id="1">Hello World!</rp>
}

func ExampleRt() {
	node := nodx.Rt(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <rt id="1">Hello World!</rt>
}

func ExampleRtc() {
	node := nodx.Rtc(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <rtc id="1">Hello World!</rtc>
}

func ExampleRuby() {
	node := nodx.Ruby(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <ruby id="1">Hello World!</ruby>
}

func ExampleS() {
	node := nodx.S(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <s id="1">Hello World!</s>
}

func ExampleSamp() {
	node := nodx.Samp(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <samp id="1">Hello World!</samp>
}

func ExampleScript() {
	node := nodx.Script(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <script id="1">Hello World!</script>
}

func ExampleSearch() {
	node := nodx.Search(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <search id="1">Hello World!</search>
}

func ExampleSection() {
	node := nodx.Section(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <section id="1">Hello World!</section>
}

func ExampleSelectEl() {
	node := nodx.SelectEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <select id="1">Hello World!</select>
}

func ExampleShadow() {
	node := nodx.Shadow(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <shadow id="1">Hello World!</shadow>
}

func ExampleSlotEl() {
	node := nodx.SlotEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <slot id="1">Hello World!</slot>
}

func ExampleSmall() {
	node := nodx.Small(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <small id="1">Hello World!</small>
}

func ExampleSource() {
	node := nodx.Source(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <source id="1">
}

func ExampleSpacer() {
	node := nodx.Spacer(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <spacer id="1">Hello World!</spacer>
}

func ExampleSpanEl() {
	node := nodx.SpanEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <span id="1">Hello World!</span>
}

func ExampleStrike() {
	node := nodx.Strike(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <strike id="1">Hello World!</strike>
}

func ExampleStrong() {
	node := nodx.Strong(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <strong id="1">Hello World!</strong>
}

func ExampleStyleEl() {
	node := nodx.StyleEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <style id="1">Hello World!</style>
}

func ExampleSub() {
	node := nodx.Sub(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <sub id="1">Hello World!</sub>
}

func ExampleSummaryEl() {
	node := nodx.SummaryEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <summary id="1">Hello World!</summary>
}

func ExampleSup() {
	node := nodx.Sup(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <sup id="1">Hello World!</sup>
}

func ExampleSvg() {
	node := nodx.Svg(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <svg id="1">Hello World!</svg>
}

func ExampleTable() {
	node := nodx.Table(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <table id="1">Hello World!</table>
}

func ExampleTbody() {
	node := nodx.Tbody(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <tbody id="1">Hello World!</tbody>
}

func ExampleTd() {
	node := nodx.Td(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <td id="1">Hello World!</td>
}

func ExampleTemplate() {
	node := nodx.Template(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <template id="1">Hello World!</template>
}

func ExampleTextarea() {
	node := nodx.Textarea(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <textarea id="1">Hello World!</textarea>
}

func ExampleTfoot() {
	node := nodx.Tfoot(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <tfoot id="1">Hello World!</tfoot>
}

func ExampleTh() {
	node := nodx.Th(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <th id="1">Hello World!</th>
}

func ExampleThead() {
	node := nodx.Thead(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <thead id="1">Hello World!</thead>
}

func ExampleTime() {
	node := nodx.Time(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <time id="1">Hello World!</time>
}

func ExampleTitleEl() {
	node := nodx.TitleEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <title id="1">Hello World!</title>
}

func ExampleTr() {
	node := nodx.Tr(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <tr id="1">Hello World!</tr>
}

func ExampleTrack() {
	node := nodx.Track(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <track id="1">
}

func ExampleTt() {
	node := nodx.Tt(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <tt id="1">Hello World!</tt>
}

func ExampleU() {
	node := nodx.U(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <u id="1">Hello World!</u>
}

func ExampleUl() {
	node := nodx.Ul(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <ul id="1">Hello World!</ul>
}

func ExampleVarEl() {
	node := nodx.VarEl(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <var id="1">Hello World!</var>
}

func ExampleVideo() {
	node := nodx.Video(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <video id="1">Hello World!</video>
}

func ExampleWbr() {
	node := nodx.Wbr(
		nodx.Id("1"),
	)
	fmt.Println(node)
	// Output: <wbr id="1">
}

func ExampleXmp() {
	node := nodx.Xmp(
		nodx.Id("1"),
		nodx.Text("Hello World!"),
	)
	fmt.Println(node)
	// Output: <xmp id="1">Hello World!</xmp>
}
