package nodx_test

// Code generated by NodX. DO NOT EDIT.

import (
	"fmt"

	nodx "github.com/varavelio/nodxgo"
)

func ExampleAbbrAttr() {
	node := nodx.AbbrAttr("value")
	fmt.Println(node)
	// Output: abbr="value"
}

func ExampleAccept() {
	node := nodx.Accept("value")
	fmt.Println(node)
	// Output: accept="value"
}

func ExampleAcceptCharset() {
	node := nodx.AcceptCharset("value")
	fmt.Println(node)
	// Output: accept-charset="value"
}

func ExampleAccesskey() {
	node := nodx.Accesskey("value")
	fmt.Println(node)
	// Output: accesskey="value"
}

func ExampleAction() {
	node := nodx.Action("value")
	fmt.Println(node)
	// Output: action="value"
}

func ExampleAlign() {
	node := nodx.Align("value")
	fmt.Println(node)
	// Output: align="value"
}

func ExampleAllow() {
	node := nodx.Allow("value")
	fmt.Println(node)
	// Output: allow="value"
}

func ExampleAllowfullscreen() {
	node := nodx.Allowfullscreen(true)
	fmt.Println(node)
	// Output: allowfullscreen
}

func ExampleAlt() {
	node := nodx.Alt("value")
	fmt.Println(node)
	// Output: alt="value"
}

func ExampleArchive() {
	node := nodx.Archive("value")
	fmt.Println(node)
	// Output: archive="value"
}

func ExampleAria() {
	node := nodx.Aria("key", "value")
	fmt.Println(node)
	// Output: aria-key="value"
}

func ExampleAs() {
	node := nodx.As("value")
	fmt.Println(node)
	// Output: as="value"
}

func ExampleAsync() {
	node := nodx.Async(true)
	fmt.Println(node)
	// Output: async
}

func ExampleAutocapitalize() {
	node := nodx.Autocapitalize("value")
	fmt.Println(node)
	// Output: autocapitalize="value"
}

func ExampleAutocomplete() {
	node := nodx.Autocomplete("value")
	fmt.Println(node)
	// Output: autocomplete="value"
}

func ExampleAutocorrect() {
	node := nodx.Autocorrect("value")
	fmt.Println(node)
	// Output: autocorrect="value"
}

func ExampleAutofocus() {
	node := nodx.Autofocus(true)
	fmt.Println(node)
	// Output: autofocus
}

func ExampleAutoplay() {
	node := nodx.Autoplay(true)
	fmt.Println(node)
	// Output: autoplay
}

func ExampleAutosave() {
	node := nodx.Autosave("value")
	fmt.Println(node)
	// Output: autosave="value"
}

func ExampleAxis() {
	node := nodx.Axis("value")
	fmt.Println(node)
	// Output: axis="value"
}

func ExampleBackground() {
	node := nodx.Background("value")
	fmt.Println(node)
	// Output: background="value"
}

func ExampleBgcolor() {
	node := nodx.Bgcolor("value")
	fmt.Println(node)
	// Output: bgcolor="value"
}

func ExampleBlocking() {
	node := nodx.Blocking("value")
	fmt.Println(node)
	// Output: blocking="value"
}

func ExampleBorder() {
	node := nodx.Border("value")
	fmt.Println(node)
	// Output: border="value"
}

func ExampleBuffered() {
	node := nodx.Buffered("value")
	fmt.Println(node)
	// Output: buffered="value"
}

func ExampleCapture() {
	node := nodx.Capture("value")
	fmt.Println(node)
	// Output: capture="value"
}

func ExampleCellpadding() {
	node := nodx.Cellpadding("value")
	fmt.Println(node)
	// Output: cellpadding="value"
}

func ExampleCellspacing() {
	node := nodx.Cellspacing("value")
	fmt.Println(node)
	// Output: cellspacing="value"
}

func ExampleChallenge() {
	node := nodx.Challenge("value")
	fmt.Println(node)
	// Output: challenge="value"
}

func ExampleChar() {
	node := nodx.Char("value")
	fmt.Println(node)
	// Output: char="value"
}

func ExampleCharoff() {
	node := nodx.Charoff("value")
	fmt.Println(node)
	// Output: charoff="value"
}

func ExampleCharset() {
	node := nodx.Charset("value")
	fmt.Println(node)
	// Output: charset="value"
}

func ExampleChecked() {
	node := nodx.Checked(true)
	fmt.Println(node)
	// Output: checked
}

func ExampleCiteAttr() {
	node := nodx.CiteAttr("value")
	fmt.Println(node)
	// Output: cite="value"
}

func ExampleClass() {
	node := nodx.Class("value")
	fmt.Println(node)
	// Output: class="value"
}

func ExampleClassid() {
	node := nodx.Classid("value")
	fmt.Println(node)
	// Output: classid="value"
}

func ExampleClear() {
	node := nodx.Clear("value")
	fmt.Println(node)
	// Output: clear="value"
}

func ExampleCodeAttr() {
	node := nodx.CodeAttr("value")
	fmt.Println(node)
	// Output: code="value"
}

func ExampleCodebase() {
	node := nodx.Codebase("value")
	fmt.Println(node)
	// Output: codebase="value"
}

func ExampleCodetype() {
	node := nodx.Codetype("value")
	fmt.Println(node)
	// Output: codetype="value"
}

func ExampleColor() {
	node := nodx.Color("value")
	fmt.Println(node)
	// Output: color="value"
}

func ExampleCols() {
	node := nodx.Cols("value")
	fmt.Println(node)
	// Output: cols="value"
}

func ExampleColspan() {
	node := nodx.Colspan("value")
	fmt.Println(node)
	// Output: colspan="value"
}

func ExampleCompact() {
	node := nodx.Compact("value")
	fmt.Println(node)
	// Output: compact="value"
}

func ExampleContentAttr() {
	node := nodx.ContentAttr("value")
	fmt.Println(node)
	// Output: content="value"
}

func ExampleContenteditable() {
	node := nodx.Contenteditable("value")
	fmt.Println(node)
	// Output: contenteditable="value"
}

func ExampleContextmenu() {
	node := nodx.Contextmenu("value")
	fmt.Println(node)
	// Output: contextmenu="value"
}

func ExampleControls() {
	node := nodx.Controls(true)
	fmt.Println(node)
	// Output: controls
}

func ExampleCoords() {
	node := nodx.Coords("value")
	fmt.Println(node)
	// Output: coords="value"
}

func ExampleCrossorigin() {
	node := nodx.Crossorigin("value")
	fmt.Println(node)
	// Output: crossorigin="value"
}

func ExampleCsp() {
	node := nodx.Csp("value")
	fmt.Println(node)
	// Output: csp="value"
}

func ExampleDataAttr() {
	node := nodx.DataAttr("value")
	fmt.Println(node)
	// Output: data="value"
}

func ExampleData() {
	node := nodx.Data("key", "value")
	fmt.Println(node)
	// Output: data-key="value"
}

func ExampleDatetime() {
	node := nodx.Datetime("value")
	fmt.Println(node)
	// Output: datetime="value"
}

func ExampleDeclare() {
	node := nodx.Declare("value")
	fmt.Println(node)
	// Output: declare="value"
}

func ExampleDecoding() {
	node := nodx.Decoding("value")
	fmt.Println(node)
	// Output: decoding="value"
}

func ExampleDefaultAttr() {
	node := nodx.DefaultAttr(true)
	fmt.Println(node)
	// Output: default
}

func ExampleDeferAttr() {
	node := nodx.DeferAttr(true)
	fmt.Println(node)
	// Output: defer
}

func ExampleDirAttr() {
	node := nodx.DirAttr("value")
	fmt.Println(node)
	// Output: dir="value"
}

func ExampleDirname() {
	node := nodx.Dirname("value")
	fmt.Println(node)
	// Output: dirname="value"
}

func ExampleDisabled() {
	node := nodx.Disabled(true)
	fmt.Println(node)
	// Output: disabled
}

func ExampleDownload() {
	node := nodx.Download("value")
	fmt.Println(node)
	// Output: download="value"
}

func ExampleDraggable() {
	node := nodx.Draggable("value")
	fmt.Println(node)
	// Output: draggable="value"
}

func ExampleEnctype() {
	node := nodx.Enctype("value")
	fmt.Println(node)
	// Output: enctype="value"
}

func ExampleEnterkeyhint() {
	node := nodx.Enterkeyhint("value")
	fmt.Println(node)
	// Output: enterkeyhint="value"
}

func ExampleEvent() {
	node := nodx.Event("value")
	fmt.Println(node)
	// Output: event="value"
}

func ExampleExportparts() {
	node := nodx.Exportparts("value")
	fmt.Println(node)
	// Output: exportparts="value"
}

func ExampleFace() {
	node := nodx.Face("value")
	fmt.Println(node)
	// Output: face="value"
}

func ExampleFetchpriority() {
	node := nodx.Fetchpriority("value")
	fmt.Println(node)
	// Output: fetchpriority="value"
}

func ExampleForAttr() {
	node := nodx.ForAttr("value")
	fmt.Println(node)
	// Output: for="value"
}

func ExampleFormAttr() {
	node := nodx.FormAttr("value")
	fmt.Println(node)
	// Output: form="value"
}

func ExampleFormaction() {
	node := nodx.Formaction("value")
	fmt.Println(node)
	// Output: formaction="value"
}

func ExampleFormenctype() {
	node := nodx.Formenctype("value")
	fmt.Println(node)
	// Output: formenctype="value"
}

func ExampleFormmethod() {
	node := nodx.Formmethod("value")
	fmt.Println(node)
	// Output: formmethod="value"
}

func ExampleFormnovalidate() {
	node := nodx.Formnovalidate(true)
	fmt.Println(node)
	// Output: formnovalidate
}

func ExampleFormtarget() {
	node := nodx.Formtarget("value")
	fmt.Println(node)
	// Output: formtarget="value"
}

func ExampleFrameAttr() {
	node := nodx.FrameAttr("value")
	fmt.Println(node)
	// Output: frame="value"
}

func ExampleFrameborder() {
	node := nodx.Frameborder("value")
	fmt.Println(node)
	// Output: frameborder="value"
}

func ExampleHeaders() {
	node := nodx.Headers("value")
	fmt.Println(node)
	// Output: headers="value"
}

func ExampleHeight() {
	node := nodx.Height("value")
	fmt.Println(node)
	// Output: height="value"
}

func ExampleHidden() {
	node := nodx.Hidden("value")
	fmt.Println(node)
	// Output: hidden="value"
}

func ExampleHigh() {
	node := nodx.High("value")
	fmt.Println(node)
	// Output: high="value"
}

func ExampleHref() {
	node := nodx.Href("value")
	fmt.Println(node)
	// Output: href="value"
}

func ExampleHreflang() {
	node := nodx.Hreflang("value")
	fmt.Println(node)
	// Output: hreflang="value"
}

func ExampleHspace() {
	node := nodx.Hspace("value")
	fmt.Println(node)
	// Output: hspace="value"
}

func ExampleHttpEquiv() {
	node := nodx.HttpEquiv("value")
	fmt.Println(node)
	// Output: http-equiv="value"
}

func ExampleIcon() {
	node := nodx.Icon("value")
	fmt.Println(node)
	// Output: icon="value"
}

func ExampleId() {
	node := nodx.Id("value")
	fmt.Println(node)
	// Output: id="value"
}

func ExampleImagesizes() {
	node := nodx.Imagesizes("value")
	fmt.Println(node)
	// Output: imagesizes="value"
}

func ExampleImagesrcset() {
	node := nodx.Imagesrcset("value")
	fmt.Println(node)
	// Output: imagesrcset="value"
}

func ExampleImportance() {
	node := nodx.Importance("value")
	fmt.Println(node)
	// Output: importance="value"
}

func ExampleInert() {
	node := nodx.Inert(true)
	fmt.Println(node)
	// Output: inert
}

func ExampleInputmode() {
	node := nodx.Inputmode("value")
	fmt.Println(node)
	// Output: inputmode="value"
}

func ExampleIntegrity() {
	node := nodx.Integrity("value")
	fmt.Println(node)
	// Output: integrity="value"
}

func ExampleIsmap() {
	node := nodx.Ismap(true)
	fmt.Println(node)
	// Output: ismap
}

func ExampleItemid() {
	node := nodx.Itemid("value")
	fmt.Println(node)
	// Output: itemid="value"
}

func ExampleItemprop() {
	node := nodx.Itemprop("value")
	fmt.Println(node)
	// Output: itemprop="value"
}

func ExampleItemref() {
	node := nodx.Itemref("value")
	fmt.Println(node)
	// Output: itemref="value"
}

func ExampleItemscope() {
	node := nodx.Itemscope(true)
	fmt.Println(node)
	// Output: itemscope
}

func ExampleItemtype() {
	node := nodx.Itemtype("value")
	fmt.Println(node)
	// Output: itemtype="value"
}

func ExampleKeytype() {
	node := nodx.Keytype("value")
	fmt.Println(node)
	// Output: keytype="value"
}

func ExampleKind() {
	node := nodx.Kind("value")
	fmt.Println(node)
	// Output: kind="value"
}

func ExampleLabelAttr() {
	node := nodx.LabelAttr("value")
	fmt.Println(node)
	// Output: label="value"
}

func ExampleLang() {
	node := nodx.Lang("value")
	fmt.Println(node)
	// Output: lang="value"
}

func ExampleLanguage() {
	node := nodx.Language("value")
	fmt.Println(node)
	// Output: language="value"
}

func ExampleList() {
	node := nodx.List("value")
	fmt.Println(node)
	// Output: list="value"
}

func ExampleLoading() {
	node := nodx.Loading("value")
	fmt.Println(node)
	// Output: loading="value"
}

func ExampleLongdesc() {
	node := nodx.Longdesc("value")
	fmt.Println(node)
	// Output: longdesc="value"
}

func ExampleLoop() {
	node := nodx.Loop(true)
	fmt.Println(node)
	// Output: loop
}

func ExampleLow() {
	node := nodx.Low("value")
	fmt.Println(node)
	// Output: low="value"
}

func ExampleManifest() {
	node := nodx.Manifest("value")
	fmt.Println(node)
	// Output: manifest="value"
}

func ExampleMarginheight() {
	node := nodx.Marginheight("value")
	fmt.Println(node)
	// Output: marginheight="value"
}

func ExampleMarginwidth() {
	node := nodx.Marginwidth("value")
	fmt.Println(node)
	// Output: marginwidth="value"
}

func ExampleMax() {
	node := nodx.Max("value")
	fmt.Println(node)
	// Output: max="value"
}

func ExampleMaxlength() {
	node := nodx.Maxlength("value")
	fmt.Println(node)
	// Output: maxlength="value"
}

func ExampleMedia() {
	node := nodx.Media("value")
	fmt.Println(node)
	// Output: media="value"
}

func ExampleMethod() {
	node := nodx.Method("value")
	fmt.Println(node)
	// Output: method="value"
}

func ExampleMin() {
	node := nodx.Min("value")
	fmt.Println(node)
	// Output: min="value"
}

func ExampleMinlength() {
	node := nodx.Minlength("value")
	fmt.Println(node)
	// Output: minlength="value"
}

func ExampleMultiple() {
	node := nodx.Multiple(true)
	fmt.Println(node)
	// Output: multiple
}

func ExampleMuted() {
	node := nodx.Muted(true)
	fmt.Println(node)
	// Output: muted
}

func ExampleName() {
	node := nodx.Name("value")
	fmt.Println(node)
	// Output: name="value"
}

func ExampleNohref() {
	node := nodx.Nohref("value")
	fmt.Println(node)
	// Output: nohref="value"
}

func ExampleNomodule() {
	node := nodx.Nomodule(true)
	fmt.Println(node)
	// Output: nomodule
}

func ExampleNonce() {
	node := nodx.Nonce("value")
	fmt.Println(node)
	// Output: nonce="value"
}

func ExampleNoresize() {
	node := nodx.Noresize("value")
	fmt.Println(node)
	// Output: noresize="value"
}

func ExampleNoshade() {
	node := nodx.Noshade("value")
	fmt.Println(node)
	// Output: noshade="value"
}

func ExampleNovalidate() {
	node := nodx.Novalidate(true)
	fmt.Println(node)
	// Output: novalidate
}

func ExampleNowrap() {
	node := nodx.Nowrap("value")
	fmt.Println(node)
	// Output: nowrap="value"
}

func ExampleOnabort() {
	node := nodx.Onabort("value")
	fmt.Println(node)
	// Output: onabort="value"
}

func ExampleOnanimationcancel() {
	node := nodx.Onanimationcancel("value")
	fmt.Println(node)
	// Output: onanimationcancel="value"
}

func ExampleOnanimationend() {
	node := nodx.Onanimationend("value")
	fmt.Println(node)
	// Output: onanimationend="value"
}

func ExampleOnanimationiteration() {
	node := nodx.Onanimationiteration("value")
	fmt.Println(node)
	// Output: onanimationiteration="value"
}

func ExampleOnanimationstart() {
	node := nodx.Onanimationstart("value")
	fmt.Println(node)
	// Output: onanimationstart="value"
}

func ExampleOnauxclick() {
	node := nodx.Onauxclick("value")
	fmt.Println(node)
	// Output: onauxclick="value"
}

func ExampleOnbeforeinput() {
	node := nodx.Onbeforeinput("value")
	fmt.Println(node)
	// Output: onbeforeinput="value"
}

func ExampleOnbeforematch() {
	node := nodx.Onbeforematch("value")
	fmt.Println(node)
	// Output: onbeforematch="value"
}

func ExampleOnbeforetoggle() {
	node := nodx.Onbeforetoggle("value")
	fmt.Println(node)
	// Output: onbeforetoggle="value"
}

func ExampleOnblur() {
	node := nodx.Onblur("value")
	fmt.Println(node)
	// Output: onblur="value"
}

func ExampleOncancel() {
	node := nodx.Oncancel("value")
	fmt.Println(node)
	// Output: oncancel="value"
}

func ExampleOncanplay() {
	node := nodx.Oncanplay("value")
	fmt.Println(node)
	// Output: oncanplay="value"
}

func ExampleOncanplaythrough() {
	node := nodx.Oncanplaythrough("value")
	fmt.Println(node)
	// Output: oncanplaythrough="value"
}

func ExampleOnchange() {
	node := nodx.Onchange("value")
	fmt.Println(node)
	// Output: onchange="value"
}

func ExampleOnclick() {
	node := nodx.Onclick("value")
	fmt.Println(node)
	// Output: onclick="value"
}

func ExampleOnclose() {
	node := nodx.Onclose("value")
	fmt.Println(node)
	// Output: onclose="value"
}

func ExampleOncontextlost() {
	node := nodx.Oncontextlost("value")
	fmt.Println(node)
	// Output: oncontextlost="value"
}

func ExampleOncontextmenu() {
	node := nodx.Oncontextmenu("value")
	fmt.Println(node)
	// Output: oncontextmenu="value"
}

func ExampleOncontextrestored() {
	node := nodx.Oncontextrestored("value")
	fmt.Println(node)
	// Output: oncontextrestored="value"
}

func ExampleOncopy() {
	node := nodx.Oncopy("value")
	fmt.Println(node)
	// Output: oncopy="value"
}

func ExampleOncuechange() {
	node := nodx.Oncuechange("value")
	fmt.Println(node)
	// Output: oncuechange="value"
}

func ExampleOncut() {
	node := nodx.Oncut("value")
	fmt.Println(node)
	// Output: oncut="value"
}

func ExampleOndblclick() {
	node := nodx.Ondblclick("value")
	fmt.Println(node)
	// Output: ondblclick="value"
}

func ExampleOndrag() {
	node := nodx.Ondrag("value")
	fmt.Println(node)
	// Output: ondrag="value"
}

func ExampleOndragend() {
	node := nodx.Ondragend("value")
	fmt.Println(node)
	// Output: ondragend="value"
}

func ExampleOndragenter() {
	node := nodx.Ondragenter("value")
	fmt.Println(node)
	// Output: ondragenter="value"
}

func ExampleOndragleave() {
	node := nodx.Ondragleave("value")
	fmt.Println(node)
	// Output: ondragleave="value"
}

func ExampleOndragover() {
	node := nodx.Ondragover("value")
	fmt.Println(node)
	// Output: ondragover="value"
}

func ExampleOndragstart() {
	node := nodx.Ondragstart("value")
	fmt.Println(node)
	// Output: ondragstart="value"
}

func ExampleOndrop() {
	node := nodx.Ondrop("value")
	fmt.Println(node)
	// Output: ondrop="value"
}

func ExampleOndurationchange() {
	node := nodx.Ondurationchange("value")
	fmt.Println(node)
	// Output: ondurationchange="value"
}

func ExampleOnemptied() {
	node := nodx.Onemptied("value")
	fmt.Println(node)
	// Output: onemptied="value"
}

func ExampleOnended() {
	node := nodx.Onended("value")
	fmt.Println(node)
	// Output: onended="value"
}

func ExampleOnerror() {
	node := nodx.Onerror("value")
	fmt.Println(node)
	// Output: onerror="value"
}

func ExampleOnfocus() {
	node := nodx.Onfocus("value")
	fmt.Println(node)
	// Output: onfocus="value"
}

func ExampleOnformdata() {
	node := nodx.Onformdata("value")
	fmt.Println(node)
	// Output: onformdata="value"
}

func ExampleOngotpointercapture() {
	node := nodx.Ongotpointercapture("value")
	fmt.Println(node)
	// Output: ongotpointercapture="value"
}

func ExampleOninput() {
	node := nodx.Oninput("value")
	fmt.Println(node)
	// Output: oninput="value"
}

func ExampleOninvalid() {
	node := nodx.Oninvalid("value")
	fmt.Println(node)
	// Output: oninvalid="value"
}

func ExampleOnkeydown() {
	node := nodx.Onkeydown("value")
	fmt.Println(node)
	// Output: onkeydown="value"
}

func ExampleOnkeypress() {
	node := nodx.Onkeypress("value")
	fmt.Println(node)
	// Output: onkeypress="value"
}

func ExampleOnkeyup() {
	node := nodx.Onkeyup("value")
	fmt.Println(node)
	// Output: onkeyup="value"
}

func ExampleOnload() {
	node := nodx.Onload("value")
	fmt.Println(node)
	// Output: onload="value"
}

func ExampleOnloadeddata() {
	node := nodx.Onloadeddata("value")
	fmt.Println(node)
	// Output: onloadeddata="value"
}

func ExampleOnloadedmetadata() {
	node := nodx.Onloadedmetadata("value")
	fmt.Println(node)
	// Output: onloadedmetadata="value"
}

func ExampleOnloadstart() {
	node := nodx.Onloadstart("value")
	fmt.Println(node)
	// Output: onloadstart="value"
}

func ExampleOnlostpointercapture() {
	node := nodx.Onlostpointercapture("value")
	fmt.Println(node)
	// Output: onlostpointercapture="value"
}

func ExampleOnmousedown() {
	node := nodx.Onmousedown("value")
	fmt.Println(node)
	// Output: onmousedown="value"
}

func ExampleOnmouseenter() {
	node := nodx.Onmouseenter("value")
	fmt.Println(node)
	// Output: onmouseenter="value"
}

func ExampleOnmouseleave() {
	node := nodx.Onmouseleave("value")
	fmt.Println(node)
	// Output: onmouseleave="value"
}

func ExampleOnmousemove() {
	node := nodx.Onmousemove("value")
	fmt.Println(node)
	// Output: onmousemove="value"
}

func ExampleOnmouseout() {
	node := nodx.Onmouseout("value")
	fmt.Println(node)
	// Output: onmouseout="value"
}

func ExampleOnmouseover() {
	node := nodx.Onmouseover("value")
	fmt.Println(node)
	// Output: onmouseover="value"
}

func ExampleOnmouseup() {
	node := nodx.Onmouseup("value")
	fmt.Println(node)
	// Output: onmouseup="value"
}

func ExampleOnpaste() {
	node := nodx.Onpaste("value")
	fmt.Println(node)
	// Output: onpaste="value"
}

func ExampleOnpause() {
	node := nodx.Onpause("value")
	fmt.Println(node)
	// Output: onpause="value"
}

func ExampleOnplay() {
	node := nodx.Onplay("value")
	fmt.Println(node)
	// Output: onplay="value"
}

func ExampleOnplaying() {
	node := nodx.Onplaying("value")
	fmt.Println(node)
	// Output: onplaying="value"
}

func ExampleOnpointercancel() {
	node := nodx.Onpointercancel("value")
	fmt.Println(node)
	// Output: onpointercancel="value"
}

func ExampleOnpointerdown() {
	node := nodx.Onpointerdown("value")
	fmt.Println(node)
	// Output: onpointerdown="value"
}

func ExampleOnpointerenter() {
	node := nodx.Onpointerenter("value")
	fmt.Println(node)
	// Output: onpointerenter="value"
}

func ExampleOnpointerleave() {
	node := nodx.Onpointerleave("value")
	fmt.Println(node)
	// Output: onpointerleave="value"
}

func ExampleOnpointermove() {
	node := nodx.Onpointermove("value")
	fmt.Println(node)
	// Output: onpointermove="value"
}

func ExampleOnpointerout() {
	node := nodx.Onpointerout("value")
	fmt.Println(node)
	// Output: onpointerout="value"
}

func ExampleOnpointerover() {
	node := nodx.Onpointerover("value")
	fmt.Println(node)
	// Output: onpointerover="value"
}

func ExampleOnpointerup() {
	node := nodx.Onpointerup("value")
	fmt.Println(node)
	// Output: onpointerup="value"
}

func ExampleOnprogress() {
	node := nodx.Onprogress("value")
	fmt.Println(node)
	// Output: onprogress="value"
}

func ExampleOnratechange() {
	node := nodx.Onratechange("value")
	fmt.Println(node)
	// Output: onratechange="value"
}

func ExampleOnreset() {
	node := nodx.Onreset("value")
	fmt.Println(node)
	// Output: onreset="value"
}

func ExampleOnresize() {
	node := nodx.Onresize("value")
	fmt.Println(node)
	// Output: onresize="value"
}

func ExampleOnscroll() {
	node := nodx.Onscroll("value")
	fmt.Println(node)
	// Output: onscroll="value"
}

func ExampleOnscrollend() {
	node := nodx.Onscrollend("value")
	fmt.Println(node)
	// Output: onscrollend="value"
}

func ExampleOnsecuritypolicyviolation() {
	node := nodx.Onsecuritypolicyviolation("value")
	fmt.Println(node)
	// Output: onsecuritypolicyviolation="value"
}

func ExampleOnseeked() {
	node := nodx.Onseeked("value")
	fmt.Println(node)
	// Output: onseeked="value"
}

func ExampleOnseeking() {
	node := nodx.Onseeking("value")
	fmt.Println(node)
	// Output: onseeking="value"
}

func ExampleOnselect() {
	node := nodx.Onselect("value")
	fmt.Println(node)
	// Output: onselect="value"
}

func ExampleOnslotchange() {
	node := nodx.Onslotchange("value")
	fmt.Println(node)
	// Output: onslotchange="value"
}

func ExampleOnstalled() {
	node := nodx.Onstalled("value")
	fmt.Println(node)
	// Output: onstalled="value"
}

func ExampleOnsubmit() {
	node := nodx.Onsubmit("value")
	fmt.Println(node)
	// Output: onsubmit="value"
}

func ExampleOnsuspend() {
	node := nodx.Onsuspend("value")
	fmt.Println(node)
	// Output: onsuspend="value"
}

func ExampleOntimeupdate() {
	node := nodx.Ontimeupdate("value")
	fmt.Println(node)
	// Output: ontimeupdate="value"
}

func ExampleOntoggle() {
	node := nodx.Ontoggle("value")
	fmt.Println(node)
	// Output: ontoggle="value"
}

func ExampleOntransitioncancel() {
	node := nodx.Ontransitioncancel("value")
	fmt.Println(node)
	// Output: ontransitioncancel="value"
}

func ExampleOntransitionend() {
	node := nodx.Ontransitionend("value")
	fmt.Println(node)
	// Output: ontransitionend="value"
}

func ExampleOntransitionrun() {
	node := nodx.Ontransitionrun("value")
	fmt.Println(node)
	// Output: ontransitionrun="value"
}

func ExampleOntransitionstart() {
	node := nodx.Ontransitionstart("value")
	fmt.Println(node)
	// Output: ontransitionstart="value"
}

func ExampleOnvolumechange() {
	node := nodx.Onvolumechange("value")
	fmt.Println(node)
	// Output: onvolumechange="value"
}

func ExampleOnwaiting() {
	node := nodx.Onwaiting("value")
	fmt.Println(node)
	// Output: onwaiting="value"
}

func ExampleOnwheel() {
	node := nodx.Onwheel("value")
	fmt.Println(node)
	// Output: onwheel="value"
}

func ExampleOpen() {
	node := nodx.Open(true)
	fmt.Println(node)
	// Output: open
}

func ExampleOptimum() {
	node := nodx.Optimum("value")
	fmt.Println(node)
	// Output: optimum="value"
}

func ExamplePart() {
	node := nodx.Part("value")
	fmt.Println(node)
	// Output: part="value"
}

func ExamplePattern() {
	node := nodx.Pattern("value")
	fmt.Println(node)
	// Output: pattern="value"
}

func ExamplePing() {
	node := nodx.Ping("value")
	fmt.Println(node)
	// Output: ping="value"
}

func ExamplePlaceholder() {
	node := nodx.Placeholder("value")
	fmt.Println(node)
	// Output: placeholder="value"
}

func ExamplePlaysinline() {
	node := nodx.Playsinline(true)
	fmt.Println(node)
	// Output: playsinline
}

func ExamplePopover() {
	node := nodx.Popover("value")
	fmt.Println(node)
	// Output: popover="value"
}

func ExamplePopovertarget() {
	node := nodx.Popovertarget("value")
	fmt.Println(node)
	// Output: popovertarget="value"
}

func ExamplePopovertargetaction() {
	node := nodx.Popovertargetaction("value")
	fmt.Println(node)
	// Output: popovertargetaction="value"
}

func ExamplePoster() {
	node := nodx.Poster("value")
	fmt.Println(node)
	// Output: poster="value"
}

func ExamplePreload() {
	node := nodx.Preload("value")
	fmt.Println(node)
	// Output: preload="value"
}

func ExampleRadiogroup() {
	node := nodx.Radiogroup("value")
	fmt.Println(node)
	// Output: radiogroup="value"
}

func ExampleReadonly() {
	node := nodx.Readonly(true)
	fmt.Println(node)
	// Output: readonly
}

func ExampleReferrerpolicy() {
	node := nodx.Referrerpolicy("value")
	fmt.Println(node)
	// Output: referrerpolicy="value"
}

func ExampleRel() {
	node := nodx.Rel("value")
	fmt.Println(node)
	// Output: rel="value"
}

func ExampleRequired() {
	node := nodx.Required(true)
	fmt.Println(node)
	// Output: required
}

func ExampleResults() {
	node := nodx.Results("value")
	fmt.Println(node)
	// Output: results="value"
}

func ExampleReversed() {
	node := nodx.Reversed(true)
	fmt.Println(node)
	// Output: reversed
}

func ExampleRole() {
	node := nodx.Role("value")
	fmt.Println(node)
	// Output: role="value"
}

func ExampleRows() {
	node := nodx.Rows("value")
	fmt.Println(node)
	// Output: rows="value"
}

func ExampleRowspan() {
	node := nodx.Rowspan("value")
	fmt.Println(node)
	// Output: rowspan="value"
}

func ExampleRules() {
	node := nodx.Rules("value")
	fmt.Println(node)
	// Output: rules="value"
}

func ExampleSandbox() {
	node := nodx.Sandbox("value")
	fmt.Println(node)
	// Output: sandbox="value"
}

func ExampleScope() {
	node := nodx.Scope("value")
	fmt.Println(node)
	// Output: scope="value"
}

func ExampleScoped() {
	node := nodx.Scoped("value")
	fmt.Println(node)
	// Output: scoped="value"
}

func ExampleScrolling() {
	node := nodx.Scrolling("value")
	fmt.Println(node)
	// Output: scrolling="value"
}

func ExampleSelected() {
	node := nodx.Selected(true)
	fmt.Println(node)
	// Output: selected
}

func ExampleShape() {
	node := nodx.Shape("value")
	fmt.Println(node)
	// Output: shape="value"
}

func ExampleSize() {
	node := nodx.Size("value")
	fmt.Println(node)
	// Output: size="value"
}

func ExampleSizes() {
	node := nodx.Sizes("value")
	fmt.Println(node)
	// Output: sizes="value"
}

func ExampleSlotAttr() {
	node := nodx.SlotAttr("value")
	fmt.Println(node)
	// Output: slot="value"
}

func ExampleSpanAttr() {
	node := nodx.SpanAttr("value")
	fmt.Println(node)
	// Output: span="value"
}

func ExampleSpellcheck() {
	node := nodx.Spellcheck("value")
	fmt.Println(node)
	// Output: spellcheck="value"
}

func ExampleSrc() {
	node := nodx.Src("value")
	fmt.Println(node)
	// Output: src="value"
}

func ExampleSrcdoc() {
	node := nodx.Srcdoc("value")
	fmt.Println(node)
	// Output: srcdoc="value"
}

func ExampleSrclang() {
	node := nodx.Srclang("value")
	fmt.Println(node)
	// Output: srclang="value"
}

func ExampleSrcset() {
	node := nodx.Srcset("value")
	fmt.Println(node)
	// Output: srcset="value"
}

func ExampleStandby() {
	node := nodx.Standby("value")
	fmt.Println(node)
	// Output: standby="value"
}

func ExampleStart() {
	node := nodx.Start("value")
	fmt.Println(node)
	// Output: start="value"
}

func ExampleStep() {
	node := nodx.Step("value")
	fmt.Println(node)
	// Output: step="value"
}

func ExampleStyleAttr() {
	node := nodx.StyleAttr("value")
	fmt.Println(node)
	// Output: style="value"
}

func ExampleSummaryAttr() {
	node := nodx.SummaryAttr("value")
	fmt.Println(node)
	// Output: summary="value"
}

func ExampleTabindex() {
	node := nodx.Tabindex("value")
	fmt.Println(node)
	// Output: tabindex="value"
}

func ExampleTarget() {
	node := nodx.Target("value")
	fmt.Println(node)
	// Output: target="value"
}

func ExampleTitleAttr() {
	node := nodx.TitleAttr("value")
	fmt.Println(node)
	// Output: title="value"
}

func ExampleTranslate() {
	node := nodx.Translate("value")
	fmt.Println(node)
	// Output: translate="value"
}

func ExampleTypeAttr() {
	node := nodx.TypeAttr("value")
	fmt.Println(node)
	// Output: type="value"
}

func ExampleUsemap() {
	node := nodx.Usemap("value")
	fmt.Println(node)
	// Output: usemap="value"
}

func ExampleValign() {
	node := nodx.Valign("value")
	fmt.Println(node)
	// Output: valign="value"
}

func ExampleValue() {
	node := nodx.Value("value")
	fmt.Println(node)
	// Output: value="value"
}

func ExampleValuetype() {
	node := nodx.Valuetype("value")
	fmt.Println(node)
	// Output: valuetype="value"
}

func ExampleVspace() {
	node := nodx.Vspace("value")
	fmt.Println(node)
	// Output: vspace="value"
}

func ExampleWidth() {
	node := nodx.Width("value")
	fmt.Println(node)
	// Output: width="value"
}

func ExampleWrap() {
	node := nodx.Wrap("value")
	fmt.Println(node)
	// Output: wrap="value"
}
