package nodx

// Code generated by NodX. DO NOT EDIT.

// AbbrAttr specifies an abbreviated version of the content in a header cell.
//
//	func ExampleAbbrAttr() {
//		node := nodx.AbbrAttr("value")
//		fmt.Println(node)
//		// Output: abbr="value"
//	}
func AbbrAttr(value string) Node {
	return Attr("abbr", value)
}

// Accept specifies the types of files that the server accepts (only for input type='file').
//
//	func ExampleAccept() {
//		node := nodx.Accept("value")
//		fmt.Println(node)
//		// Output: accept="value"
//	}
func Accept(value string) Node {
	return Attr("accept", value)
}

// AcceptCharset specifies the character encodings to be used for form submission.
//
//	func ExampleAcceptCharset() {
//		node := nodx.AcceptCharset("value")
//		fmt.Println(node)
//		// Output: accept-charset="value"
//	}
func AcceptCharset(value string) Node {
	return Attr("accept-charset", value)
}

// Accesskey specifies a shortcut key to activate/focus an element.
//
//	func ExampleAccesskey() {
//		node := nodx.Accesskey("value")
//		fmt.Println(node)
//		// Output: accesskey="value"
//	}
func Accesskey(value string) Node {
	return Attr("accesskey", value)
}

// Action specifies where to send the form-data when a form is submitted.
//
//	func ExampleAction() {
//		node := nodx.Action("value")
//		fmt.Println(node)
//		// Output: action="value"
//	}
func Action(value string) Node {
	return Attr("action", value)
}

// Align specifies the alignment of the element's content.
//
//	func ExampleAlign() {
//		node := nodx.Align("value")
//		fmt.Println(node)
//		// Output: align="value"
//	}
func Align(value string) Node {
	return Attr("align", value)
}

// Allow specifies a feature policy for the iframe.
//
//	func ExampleAllow() {
//		node := nodx.Allow("value")
//		fmt.Println(node)
//		// Output: allow="value"
//	}
func Allow(value string) Node {
	return Attr("allow", value)
}

// Allowfullscreen specifies that an iframe can be displayed in fullscreen mode.
//
//	func ExampleAllowfullscreen() {
//		node := nodx.Allowfullscreen("value")
//		fmt.Println(node)
//		// Output: allowfullscreen="value"
//	}
func Allowfullscreen(value string) Node {
	return Attr("allowfullscreen", value)
}

// Alt provides alternative text for an image if it cannot be displayed.
//
//	func ExampleAlt() {
//		node := nodx.Alt("value")
//		fmt.Println(node)
//		// Output: alt="value"
//	}
func Alt(value string) Node {
	return Attr("alt", value)
}

// Archive specifies a space-separated list of archives for an object (deprecated).
//
//	func ExampleArchive() {
//		node := nodx.Archive("value")
//		fmt.Println(node)
//		// Output: archive="value"
//	}
func Archive(value string) Node {
	return Attr("archive", value)
}

// Aria defines accessibility semantics or aria properties.
//
//	func ExampleAria() {
//		node := nodx.Aria("key", "value")
//		fmt.Println(node)
//		// Output: aria-key="value"
//	}
func Aria(key, value string) Node {
	return Attr("aria-"+key, value)
}

// As specifies the type of content being preloaded (for link rel='preload').
//
//	func ExampleAs() {
//		node := nodx.As("value")
//		fmt.Println(node)
//		// Output: as="value"
//	}
func As(value string) Node {
	return Attr("as", value)
}

// Async indicates that the script should be executed asynchronously.
//
//	func ExampleAsync() {
//		node := nodx.Async("value")
//		fmt.Println(node)
//		// Output: async="value"
//	}
func Async(value string) Node {
	return Attr("async", value)
}

// Autocapitalize controls how text input is automatically capitalized.
//
//	func ExampleAutocapitalize() {
//		node := nodx.Autocapitalize("value")
//		fmt.Println(node)
//		// Output: autocapitalize="value"
//	}
func Autocapitalize(value string) Node {
	return Attr("autocapitalize", value)
}

// Autocomplete specifies whether an input field should have autocomplete enabled.
//
//	func ExampleAutocomplete() {
//		node := nodx.Autocomplete("value")
//		fmt.Println(node)
//		// Output: autocomplete="value"
//	}
func Autocomplete(value string) Node {
	return Attr("autocomplete", value)
}

// Autocorrect controls whether automatic spelling correction is enabled for a form field.
//
//	func ExampleAutocorrect() {
//		node := nodx.Autocorrect("value")
//		fmt.Println(node)
//		// Output: autocorrect="value"
//	}
func Autocorrect(value string) Node {
	return Attr("autocorrect", value)
}

// Autofocus specifies that an input field should automatically get focus when the page loads.
//
//	func ExampleAutofocus() {
//		node := nodx.Autofocus("value")
//		fmt.Println(node)
//		// Output: autofocus="value"
//	}
func Autofocus(value string) Node {
	return Attr("autofocus", value)
}

// Autoplay specifies that the audio/video should start playing as soon as it is ready.
//
//	func ExampleAutoplay() {
//		node := nodx.Autoplay("value")
//		fmt.Println(node)
//		// Output: autoplay="value"
//	}
func Autoplay(value string) Node {
	return Attr("autoplay", value)
}

// Autosave specifies that an input should be pre-filled with previous values (deprecated).
//
//	func ExampleAutosave() {
//		node := nodx.Autosave("value")
//		fmt.Println(node)
//		// Output: autosave="value"
//	}
func Autosave(value string) Node {
	return Attr("autosave", value)
}

// Axis specifies a category name for a table cell (deprecated).
//
//	func ExampleAxis() {
//		node := nodx.Axis("value")
//		fmt.Println(node)
//		// Output: axis="value"
//	}
func Axis(value string) Node {
	return Attr("axis", value)
}

// Background specifies a background image for the element.
//
//	func ExampleBackground() {
//		node := nodx.Background("value")
//		fmt.Println(node)
//		// Output: background="value"
//	}
func Background(value string) Node {
	return Attr("background", value)
}

// Bgcolor specifies the background color of an element.
//
//	func ExampleBgcolor() {
//		node := nodx.Bgcolor("value")
//		fmt.Println(node)
//		// Output: bgcolor="value"
//	}
func Bgcolor(value string) Node {
	return Attr("bgcolor", value)
}

// Blocking specifies that a script or stylesheet blocks rendering while loading.
//
//	func ExampleBlocking() {
//		node := nodx.Blocking("value")
//		fmt.Println(node)
//		// Output: blocking="value"
//	}
func Blocking(value string) Node {
	return Attr("blocking", value)
}

// Border specifies the border width.
//
//	func ExampleBorder() {
//		node := nodx.Border("value")
//		fmt.Println(node)
//		// Output: border="value"
//	}
func Border(value string) Node {
	return Attr("border", value)
}

// Buffered contains the time ranges that the media element has buffered.
//
//	func ExampleBuffered() {
//		node := nodx.Buffered("value")
//		fmt.Println(node)
//		// Output: buffered="value"
//	}
func Buffered(value string) Node {
	return Attr("buffered", value)
}

// Capture specifies that the camera should be used for input.
//
//	func ExampleCapture() {
//		node := nodx.Capture("value")
//		fmt.Println(node)
//		// Output: capture="value"
//	}
func Capture(value string) Node {
	return Attr("capture", value)
}

// Cellpadding specifies the space between cell walls and cell content (deprecated).
//
//	func ExampleCellpadding() {
//		node := nodx.Cellpadding("value")
//		fmt.Println(node)
//		// Output: cellpadding="value"
//	}
func Cellpadding(value string) Node {
	return Attr("cellpadding", value)
}

// Cellspacing specifies the space between cells (deprecated).
//
//	func ExampleCellspacing() {
//		node := nodx.Cellspacing("value")
//		fmt.Println(node)
//		// Output: cellspacing="value"
//	}
func Cellspacing(value string) Node {
	return Attr("cellspacing", value)
}

// Challenge specifies that the value of the keygen element should be challenged when submitted.
//
//	func ExampleChallenge() {
//		node := nodx.Challenge("value")
//		fmt.Println(node)
//		// Output: challenge="value"
//	}
func Challenge(value string) Node {
	return Attr("challenge", value)
}

// Char aligns table content relative to a character (deprecated).
//
//	func ExampleChar() {
//		node := nodx.Char("value")
//		fmt.Println(node)
//		// Output: char="value"
//	}
func Char(value string) Node {
	return Attr("char", value)
}

// Charoff specifies the offset for the char attribute (deprecated).
//
//	func ExampleCharoff() {
//		node := nodx.Charoff("value")
//		fmt.Println(node)
//		// Output: charoff="value"
//	}
func Charoff(value string) Node {
	return Attr("charoff", value)
}

// Charset specifies the character encoding.
//
//	func ExampleCharset() {
//		node := nodx.Charset("value")
//		fmt.Println(node)
//		// Output: charset="value"
//	}
func Charset(value string) Node {
	return Attr("charset", value)
}

// Checked specifies that an input element should be pre-selected when the page loads.
//
//	func ExampleChecked() {
//		node := nodx.Checked("value")
//		fmt.Println(node)
//		// Output: checked="value"
//	}
func Checked(value string) Node {
	return Attr("checked", value)
}

// CiteAttr specifies a URL that explains the quote, or why a text was inserted/deleted.
//
//	func ExampleCiteAttr() {
//		node := nodx.CiteAttr("value")
//		fmt.Println(node)
//		// Output: cite="value"
//	}
func CiteAttr(value string) Node {
	return Attr("cite", value)
}

// Class specifies one or more class names for an element.
//
//	func ExampleClass() {
//		node := nodx.Class("value")
//		fmt.Println(node)
//		// Output: class="value"
//	}
func Class(value string) Node {
	return Attr("class", value)
}

// Classid specifies the class id of an object (deprecated).
//
//	func ExampleClassid() {
//		node := nodx.Classid("value")
//		fmt.Println(node)
//		// Output: classid="value"
//	}
func Classid(value string) Node {
	return Attr("classid", value)
}

// Clear specifies where the next line should appear after a line break (deprecated).
//
//	func ExampleClear() {
//		node := nodx.Clear("value")
//		fmt.Println(node)
//		// Output: clear="value"
//	}
func Clear(value string) Node {
	return Attr("clear", value)
}

// CodeAttr specifies the URL of the applet's class file to be loaded and executed.
//
//	func ExampleCodeAttr() {
//		node := nodx.CodeAttr("value")
//		fmt.Println(node)
//		// Output: code="value"
//	}
func CodeAttr(value string) Node {
	return Attr("code", value)
}

// Codebase specifies the base URL for an applet.
//
//	func ExampleCodebase() {
//		node := nodx.Codebase("value")
//		fmt.Println(node)
//		// Output: codebase="value"
//	}
func Codebase(value string) Node {
	return Attr("codebase", value)
}

// Codetype specifies the MIME type of the code of an object (deprecated).
//
//	func ExampleCodetype() {
//		node := nodx.Codetype("value")
//		fmt.Println(node)
//		// Output: codetype="value"
//	}
func Codetype(value string) Node {
	return Attr("codetype", value)
}

// Color specifies the text color of an element.
//
//	func ExampleColor() {
//		node := nodx.Color("value")
//		fmt.Println(node)
//		// Output: color="value"
//	}
func Color(value string) Node {
	return Attr("color", value)
}

// Cols specifies the visible width of a text area.
//
//	func ExampleCols() {
//		node := nodx.Cols("value")
//		fmt.Println(node)
//		// Output: cols="value"
//	}
func Cols(value string) Node {
	return Attr("cols", value)
}

// Colspan specifies the number of columns a cell should span.
//
//	func ExampleColspan() {
//		node := nodx.Colspan("value")
//		fmt.Println(node)
//		// Output: colspan="value"
//	}
func Colspan(value string) Node {
	return Attr("colspan", value)
}

// Compact specifies that a list should be rendered more compactly (deprecated).
//
//	func ExampleCompact() {
//		node := nodx.Compact("value")
//		fmt.Println(node)
//		// Output: compact="value"
//	}
func Compact(value string) Node {
	return Attr("compact", value)
}

// ContentAttr gives the value associated with the http-equiv or name attribute.
//
//	func ExampleContentAttr() {
//		node := nodx.ContentAttr("value")
//		fmt.Println(node)
//		// Output: content="value"
//	}
func ContentAttr(value string) Node {
	return Attr("content", value)
}

// Contenteditable specifies whether the content of an element is editable.
//
//	func ExampleContenteditable() {
//		node := nodx.Contenteditable("value")
//		fmt.Println(node)
//		// Output: contenteditable="value"
//	}
func Contenteditable(value string) Node {
	return Attr("contenteditable", value)
}

// Contextmenu specifies a context menu for an element.
//
//	func ExampleContextmenu() {
//		node := nodx.Contextmenu("value")
//		fmt.Println(node)
//		// Output: contextmenu="value"
//	}
func Contextmenu(value string) Node {
	return Attr("contextmenu", value)
}

// Controls specifies that audio/video controls should be displayed.
//
//	func ExampleControls() {
//		node := nodx.Controls("value")
//		fmt.Println(node)
//		// Output: controls="value"
//	}
func Controls(value string) Node {
	return Attr("controls", value)
}

// Coords specifies the coordinates of an area in an image-map.
//
//	func ExampleCoords() {
//		node := nodx.Coords("value")
//		fmt.Println(node)
//		// Output: coords="value"
//	}
func Coords(value string) Node {
	return Attr("coords", value)
}

// Crossorigin configures the CORS requests for the element's fetched data.
//
//	func ExampleCrossorigin() {
//		node := nodx.Crossorigin("value")
//		fmt.Println(node)
//		// Output: crossorigin="value"
//	}
func Crossorigin(value string) Node {
	return Attr("crossorigin", value)
}

// Csp allows specifying a Content Security Policy for the content in the iframe.
//
//	func ExampleCsp() {
//		node := nodx.Csp("value")
//		fmt.Println(node)
//		// Output: csp="value"
//	}
func Csp(value string) Node {
	return Attr("csp", value)
}

// DataAttr specifies the URL of the resource to be used by the object.
//
//	func ExampleDataAttr() {
//		node := nodx.DataAttr("value")
//		fmt.Println(node)
//		// Output: data="value"
//	}
func DataAttr(value string) Node {
	return Attr("data", value)
}

// Data used to store custom data private to the page or application.
//
//	func ExampleData() {
//		node := nodx.Data("key", "value")
//		fmt.Println(node)
//		// Output: data-key="value"
//	}
func Data(key, value string) Node {
	return Attr("data-"+key, value)
}

// Datetime specifies the date and time.
//
//	func ExampleDatetime() {
//		node := nodx.Datetime("value")
//		fmt.Println(node)
//		// Output: datetime="value"
//	}
func Datetime(value string) Node {
	return Attr("datetime", value)
}

// Declare declares an object without instantiating it (deprecated).
//
//	func ExampleDeclare() {
//		node := nodx.Declare("value")
//		fmt.Println(node)
//		// Output: declare="value"
//	}
func Declare(value string) Node {
	return Attr("declare", value)
}

// Decoding indicates how the browser should load the image.
//
//	func ExampleDecoding() {
//		node := nodx.Decoding("value")
//		fmt.Println(node)
//		// Output: decoding="value"
//	}
func Decoding(value string) Node {
	return Attr("decoding", value)
}

// Default specifies the default track kind.
//
//	func ExampleDefault() {
//		node := nodx.Default("value")
//		fmt.Println(node)
//		// Output: default="value"
//	}
func Default(value string) Node {
	return Attr("default", value)
}

// Defer specifies that the script is executed when the page has finished parsing.
//
//	func ExampleDefer() {
//		node := nodx.Defer("value")
//		fmt.Println(node)
//		// Output: defer="value"
//	}
func Defer(value string) Node {
	return Attr("defer", value)
}

// DirAttr specifies the text direction for the content.
//
//	func ExampleDirAttr() {
//		node := nodx.DirAttr("value")
//		fmt.Println(node)
//		// Output: dir="value"
//	}
func DirAttr(value string) Node {
	return Attr("dir", value)
}

// Dirname enables the submission of the text directionality of an input field.
//
//	func ExampleDirname() {
//		node := nodx.Dirname("value")
//		fmt.Println(node)
//		// Output: dirname="value"
//	}
func Dirname(value string) Node {
	return Attr("dirname", value)
}

// Disabled specifies that an element should be disabled.
//
//	func ExampleDisabled() {
//		node := nodx.Disabled("value")
//		fmt.Println(node)
//		// Output: disabled="value"
//	}
func Disabled(value string) Node {
	return Attr("disabled", value)
}

// Download specifies that the target will be downloaded when a user clicks on the hyperlink.
//
//	func ExampleDownload() {
//		node := nodx.Download("value")
//		fmt.Println(node)
//		// Output: download="value"
//	}
func Download(value string) Node {
	return Attr("download", value)
}

// Draggable specifies whether an element is draggable or not.
//
//	func ExampleDraggable() {
//		node := nodx.Draggable("value")
//		fmt.Println(node)
//		// Output: draggable="value"
//	}
func Draggable(value string) Node {
	return Attr("draggable", value)
}

// Enctype specifies how the form-data should be encoded when submitting it to the server.
//
//	func ExampleEnctype() {
//		node := nodx.Enctype("value")
//		fmt.Println(node)
//		// Output: enctype="value"
//	}
func Enctype(value string) Node {
	return Attr("enctype", value)
}

// Enterkeyhint specifies what action label to present for the enter key on virtual keyboards.
//
//	func ExampleEnterkeyhint() {
//		node := nodx.Enterkeyhint("value")
//		fmt.Println(node)
//		// Output: enterkeyhint="value"
//	}
func Enterkeyhint(value string) Node {
	return Attr("enterkeyhint", value)
}

// Event specifies the event a script is triggered by (deprecated).
//
//	func ExampleEvent() {
//		node := nodx.Event("value")
//		fmt.Println(node)
//		// Output: event="value"
//	}
func Event(value string) Node {
	return Attr("event", value)
}

// Exportparts exports shadow DOM parts of an element to its host page.
//
//	func ExampleExportparts() {
//		node := nodx.Exportparts("value")
//		fmt.Println(node)
//		// Output: exportparts="value"
//	}
func Exportparts(value string) Node {
	return Attr("exportparts", value)
}

// Face specifies the font family of the text (deprecated).
//
//	func ExampleFace() {
//		node := nodx.Face("value")
//		fmt.Println(node)
//		// Output: face="value"
//	}
func Face(value string) Node {
	return Attr("face", value)
}

// Fetchpriority hints the priority for fetching a resource.
//
//	func ExampleFetchpriority() {
//		node := nodx.Fetchpriority("value")
//		fmt.Println(node)
//		// Output: fetchpriority="value"
//	}
func Fetchpriority(value string) Node {
	return Attr("fetchpriority", value)
}

// For specifies which form element a label or output element is bound to.
//
//	func ExampleFor() {
//		node := nodx.For("value")
//		fmt.Println(node)
//		// Output: for="value"
//	}
func For(value string) Node {
	return Attr("for", value)
}

// FormAttr specifies the form the element belongs to.
//
//	func ExampleFormAttr() {
//		node := nodx.FormAttr("value")
//		fmt.Println(node)
//		// Output: form="value"
//	}
func FormAttr(value string) Node {
	return Attr("form", value)
}

// Formaction specifies where to send the form-data when a form is submitted (for input and button elements).
//
//	func ExampleFormaction() {
//		node := nodx.Formaction("value")
//		fmt.Println(node)
//		// Output: formaction="value"
//	}
func Formaction(value string) Node {
	return Attr("formaction", value)
}

// Formenctype specifies how form-data should be encoded (for input and button elements).
//
//	func ExampleFormenctype() {
//		node := nodx.Formenctype("value")
//		fmt.Println(node)
//		// Output: formenctype="value"
//	}
func Formenctype(value string) Node {
	return Attr("formenctype", value)
}

// Formmethod defines the HTTP method for sending form-data (for input and button elements).
//
//	func ExampleFormmethod() {
//		node := nodx.Formmethod("value")
//		fmt.Println(node)
//		// Output: formmethod="value"
//	}
func Formmethod(value string) Node {
	return Attr("formmethod", value)
}

// Formnovalidate defines that form elements should not be validated when submitted.
//
//	func ExampleFormnovalidate() {
//		node := nodx.Formnovalidate("value")
//		fmt.Println(node)
//		// Output: formnovalidate="value"
//	}
func Formnovalidate(value string) Node {
	return Attr("formnovalidate", value)
}

// Formtarget specifies where to display the response after submitting the form.
//
//	func ExampleFormtarget() {
//		node := nodx.Formtarget("value")
//		fmt.Println(node)
//		// Output: formtarget="value"
//	}
func Formtarget(value string) Node {
	return Attr("formtarget", value)
}

// FrameAttr specifies which parts of the table border should be visible (deprecated).
//
//	func ExampleFrameAttr() {
//		node := nodx.FrameAttr("value")
//		fmt.Println(node)
//		// Output: frame="value"
//	}
func FrameAttr(value string) Node {
	return Attr("frame", value)
}

// Frameborder specifies whether to display a border around an iframe (deprecated).
//
//	func ExampleFrameborder() {
//		node := nodx.Frameborder("value")
//		fmt.Println(node)
//		// Output: frameborder="value"
//	}
func Frameborder(value string) Node {
	return Attr("frameborder", value)
}

// Headers specifies one or more header cells a cell is related to.
//
//	func ExampleHeaders() {
//		node := nodx.Headers("value")
//		fmt.Println(node)
//		// Output: headers="value"
//	}
func Headers(value string) Node {
	return Attr("headers", value)
}

// Height specifies the height of the element.
//
//	func ExampleHeight() {
//		node := nodx.Height("value")
//		fmt.Println(node)
//		// Output: height="value"
//	}
func Height(value string) Node {
	return Attr("height", value)
}

// Hidden specifies that an element is not yet, or is no longer, relevant.
//
//	func ExampleHidden() {
//		node := nodx.Hidden("value")
//		fmt.Println(node)
//		// Output: hidden="value"
//	}
func Hidden(value string) Node {
	return Attr("hidden", value)
}

// High specifies the range that is considered to be a high value.
//
//	func ExampleHigh() {
//		node := nodx.High("value")
//		fmt.Println(node)
//		// Output: high="value"
//	}
func High(value string) Node {
	return Attr("high", value)
}

// Href specifies the URL of the page the link goes to.
//
//	func ExampleHref() {
//		node := nodx.Href("value")
//		fmt.Println(node)
//		// Output: href="value"
//	}
func Href(value string) Node {
	return Attr("href", value)
}

// Hreflang specifies the language of the linked document.
//
//	func ExampleHreflang() {
//		node := nodx.Hreflang("value")
//		fmt.Println(node)
//		// Output: hreflang="value"
//	}
func Hreflang(value string) Node {
	return Attr("hreflang", value)
}

// Hspace specifies the horizontal space around an element (deprecated).
//
//	func ExampleHspace() {
//		node := nodx.Hspace("value")
//		fmt.Println(node)
//		// Output: hspace="value"
//	}
func Hspace(value string) Node {
	return Attr("hspace", value)
}

// HttpEquiv provides an HTTP header for the information/value of the content attribute.
//
//	func ExampleHttpEquiv() {
//		node := nodx.HttpEquiv("value")
//		fmt.Println(node)
//		// Output: http-equiv="value"
//	}
func HttpEquiv(value string) Node {
	return Attr("http-equiv", value)
}

// Icon specifies an icon for the command.
//
//	func ExampleIcon() {
//		node := nodx.Icon("value")
//		fmt.Println(node)
//		// Output: icon="value"
//	}
func Icon(value string) Node {
	return Attr("icon", value)
}

// Id specifies a unique id for an element.
//
//	func ExampleId() {
//		node := nodx.Id("value")
//		fmt.Println(node)
//		// Output: id="value"
//	}
func Id(value string) Node {
	return Attr("id", value)
}

// Imagesizes specifies image sizes for preloaded images (link rel='preload').
//
//	func ExampleImagesizes() {
//		node := nodx.Imagesizes("value")
//		fmt.Println(node)
//		// Output: imagesizes="value"
//	}
func Imagesizes(value string) Node {
	return Attr("imagesizes", value)
}

// Imagesrcset specifies image candidates for preloaded images (link rel='preload').
//
//	func ExampleImagesrcset() {
//		node := nodx.Imagesrcset("value")
//		fmt.Println(node)
//		// Output: imagesrcset="value"
//	}
func Imagesrcset(value string) Node {
	return Attr("imagesrcset", value)
}

// Importance indicates the relative fetch priority for the resource.
//
//	func ExampleImportance() {
//		node := nodx.Importance("value")
//		fmt.Println(node)
//		// Output: importance="value"
//	}
func Importance(value string) Node {
	return Attr("importance", value)
}

// Inert makes an element and its children unresponsive to user input.
//
//	func ExampleInert() {
//		node := nodx.Inert("value")
//		fmt.Println(node)
//		// Output: inert="value"
//	}
func Inert(value string) Node {
	return Attr("inert", value)
}

// Inputmode hints the type of virtual keyboard to use for a form field.
//
//	func ExampleInputmode() {
//		node := nodx.Inputmode("value")
//		fmt.Println(node)
//		// Output: inputmode="value"
//	}
func Inputmode(value string) Node {
	return Attr("inputmode", value)
}

// Integrity allows a browser to verify the fetched resource's integrity.
//
//	func ExampleIntegrity() {
//		node := nodx.Integrity("value")
//		fmt.Println(node)
//		// Output: integrity="value"
//	}
func Integrity(value string) Node {
	return Attr("integrity", value)
}

// Ismap specifies an image as a server-side image-map.
//
//	func ExampleIsmap() {
//		node := nodx.Ismap("value")
//		fmt.Println(node)
//		// Output: ismap="value"
//	}
func Ismap(value string) Node {
	return Attr("ismap", value)
}

// Itemid specifies a global identifier for a microdata item.
//
//	func ExampleItemid() {
//		node := nodx.Itemid("value")
//		fmt.Println(node)
//		// Output: itemid="value"
//	}
func Itemid(value string) Node {
	return Attr("itemid", value)
}

// Itemprop defines a property of an item.
//
//	func ExampleItemprop() {
//		node := nodx.Itemprop("value")
//		fmt.Println(node)
//		// Output: itemprop="value"
//	}
func Itemprop(value string) Node {
	return Attr("itemprop", value)
}

// Itemref references additional elements that provide properties for a microdata item.
//
//	func ExampleItemref() {
//		node := nodx.Itemref("value")
//		fmt.Println(node)
//		// Output: itemref="value"
//	}
func Itemref(value string) Node {
	return Attr("itemref", value)
}

// Itemscope creates a microdata item.
//
//	func ExampleItemscope() {
//		node := nodx.Itemscope("value")
//		fmt.Println(node)
//		// Output: itemscope="value"
//	}
func Itemscope(value string) Node {
	return Attr("itemscope", value)
}

// Itemtype specifies the vocabulary used by a microdata item.
//
//	func ExampleItemtype() {
//		node := nodx.Itemtype("value")
//		fmt.Println(node)
//		// Output: itemtype="value"
//	}
func Itemtype(value string) Node {
	return Attr("itemtype", value)
}

// Keytype specifies the security algorithm of a key.
//
//	func ExampleKeytype() {
//		node := nodx.Keytype("value")
//		fmt.Println(node)
//		// Output: keytype="value"
//	}
func Keytype(value string) Node {
	return Attr("keytype", value)
}

// Kind specifies the kind of text track.
//
//	func ExampleKind() {
//		node := nodx.Kind("value")
//		fmt.Println(node)
//		// Output: kind="value"
//	}
func Kind(value string) Node {
	return Attr("kind", value)
}

// LabelAttr specifies the title of the text track.
//
//	func ExampleLabelAttr() {
//		node := nodx.LabelAttr("value")
//		fmt.Println(node)
//		// Output: label="value"
//	}
func LabelAttr(value string) Node {
	return Attr("label", value)
}

// Lang specifies the language of the element's content.
//
//	func ExampleLang() {
//		node := nodx.Lang("value")
//		fmt.Println(node)
//		// Output: lang="value"
//	}
func Lang(value string) Node {
	return Attr("lang", value)
}

// Language deprecated. Specifies the scripting language used for the script.
//
//	func ExampleLanguage() {
//		node := nodx.Language("value")
//		fmt.Println(node)
//		// Output: language="value"
//	}
func Language(value string) Node {
	return Attr("language", value)
}

// List refers to a datalist element that contains pre-defined options.
//
//	func ExampleList() {
//		node := nodx.List("value")
//		fmt.Println(node)
//		// Output: list="value"
//	}
func List(value string) Node {
	return Attr("list", value)
}

// Loading indicates how the browser should load the image or iframe.
//
//	func ExampleLoading() {
//		node := nodx.Loading("value")
//		fmt.Println(node)
//		// Output: loading="value"
//	}
func Loading(value string) Node {
	return Attr("loading", value)
}

// Longdesc specifies a URL with a detailed description of an image (deprecated).
//
//	func ExampleLongdesc() {
//		node := nodx.Longdesc("value")
//		fmt.Println(node)
//		// Output: longdesc="value"
//	}
func Longdesc(value string) Node {
	return Attr("longdesc", value)
}

// Loop specifies that the audio/video will start over again, every time it is finished.
//
//	func ExampleLoop() {
//		node := nodx.Loop("value")
//		fmt.Println(node)
//		// Output: loop="value"
//	}
func Loop(value string) Node {
	return Attr("loop", value)
}

// Low specifies the range that is considered to be a low value.
//
//	func ExampleLow() {
//		node := nodx.Low("value")
//		fmt.Println(node)
//		// Output: low="value"
//	}
func Low(value string) Node {
	return Attr("low", value)
}

// Manifest specifies the URL of the document's cache manifest.
//
//	func ExampleManifest() {
//		node := nodx.Manifest("value")
//		fmt.Println(node)
//		// Output: manifest="value"
//	}
func Manifest(value string) Node {
	return Attr("manifest", value)
}

// Marginheight specifies the top and bottom margins of an iframe (deprecated).
//
//	func ExampleMarginheight() {
//		node := nodx.Marginheight("value")
//		fmt.Println(node)
//		// Output: marginheight="value"
//	}
func Marginheight(value string) Node {
	return Attr("marginheight", value)
}

// Marginwidth specifies the left and right margins of an iframe (deprecated).
//
//	func ExampleMarginwidth() {
//		node := nodx.Marginwidth("value")
//		fmt.Println(node)
//		// Output: marginwidth="value"
//	}
func Marginwidth(value string) Node {
	return Attr("marginwidth", value)
}

// Max specifies the maximum value.
//
//	func ExampleMax() {
//		node := nodx.Max("value")
//		fmt.Println(node)
//		// Output: max="value"
//	}
func Max(value string) Node {
	return Attr("max", value)
}

// Maxlength specifies the maximum number of characters allowed in an input field.
//
//	func ExampleMaxlength() {
//		node := nodx.Maxlength("value")
//		fmt.Println(node)
//		// Output: maxlength="value"
//	}
func Maxlength(value string) Node {
	return Attr("maxlength", value)
}

// Media specifies what media/device the linked document is optimized for.
//
//	func ExampleMedia() {
//		node := nodx.Media("value")
//		fmt.Println(node)
//		// Output: media="value"
//	}
func Media(value string) Node {
	return Attr("media", value)
}

// Method specifies the HTTP method to use when sending form-data.
//
//	func ExampleMethod() {
//		node := nodx.Method("value")
//		fmt.Println(node)
//		// Output: method="value"
//	}
func Method(value string) Node {
	return Attr("method", value)
}

// Min specifies the minimum value.
//
//	func ExampleMin() {
//		node := nodx.Min("value")
//		fmt.Println(node)
//		// Output: min="value"
//	}
func Min(value string) Node {
	return Attr("min", value)
}

// Minlength specifies the minimum number of characters required in an input field.
//
//	func ExampleMinlength() {
//		node := nodx.Minlength("value")
//		fmt.Println(node)
//		// Output: minlength="value"
//	}
func Minlength(value string) Node {
	return Attr("minlength", value)
}

// Multiple specifies that a user can enter more than one value.
//
//	func ExampleMultiple() {
//		node := nodx.Multiple("value")
//		fmt.Println(node)
//		// Output: multiple="value"
//	}
func Multiple(value string) Node {
	return Attr("multiple", value)
}

// Muted specifies that the audio output should be muted.
//
//	func ExampleMuted() {
//		node := nodx.Muted("value")
//		fmt.Println(node)
//		// Output: muted="value"
//	}
func Muted(value string) Node {
	return Attr("muted", value)
}

// Name specifies the name of the element.
//
//	func ExampleName() {
//		node := nodx.Name("value")
//		fmt.Println(node)
//		// Output: name="value"
//	}
func Name(value string) Node {
	return Attr("name", value)
}

// Nohref specifies that an area has no associated link (deprecated).
//
//	func ExampleNohref() {
//		node := nodx.Nohref("value")
//		fmt.Println(node)
//		// Output: nohref="value"
//	}
func Nohref(value string) Node {
	return Attr("nohref", value)
}

// Nomodule indicates that the script should not be executed in browsers that support module scripts.
//
//	func ExampleNomodule() {
//		node := nodx.Nomodule("value")
//		fmt.Println(node)
//		// Output: nomodule="value"
//	}
func Nomodule(value string) Node {
	return Attr("nomodule", value)
}

// Nonce a cryptographic nonce used in Content Security Policy.
//
//	func ExampleNonce() {
//		node := nodx.Nonce("value")
//		fmt.Println(node)
//		// Output: nonce="value"
//	}
func Nonce(value string) Node {
	return Attr("nonce", value)
}

// Noresize specifies that a frame cannot be resized (deprecated).
//
//	func ExampleNoresize() {
//		node := nodx.Noresize("value")
//		fmt.Println(node)
//		// Output: noresize="value"
//	}
func Noresize(value string) Node {
	return Attr("noresize", value)
}

// Noshade specifies that a horizontal rule has no shading (deprecated).
//
//	func ExampleNoshade() {
//		node := nodx.Noshade("value")
//		fmt.Println(node)
//		// Output: noshade="value"
//	}
func Noshade(value string) Node {
	return Attr("noshade", value)
}

// Novalidate specifies that the form should not be validated when submitted.
//
//	func ExampleNovalidate() {
//		node := nodx.Novalidate("value")
//		fmt.Println(node)
//		// Output: novalidate="value"
//	}
func Novalidate(value string) Node {
	return Attr("novalidate", value)
}

// Nowrap specifies that content should not wrap (deprecated).
//
//	func ExampleNowrap() {
//		node := nodx.Nowrap("value")
//		fmt.Println(node)
//		// Output: nowrap="value"
//	}
func Nowrap(value string) Node {
	return Attr("nowrap", value)
}

// Onabort fires when the loading of a resource is aborted.
//
//	func ExampleOnabort() {
//		node := nodx.Onabort("value")
//		fmt.Println(node)
//		// Output: onabort="value"
//	}
func Onabort(value string) Node {
	return Attr("onabort", value)
}

// Onanimationcancel fires when a CSS animation is unexpectedly interrupted.
//
//	func ExampleOnanimationcancel() {
//		node := nodx.Onanimationcancel("value")
//		fmt.Println(node)
//		// Output: onanimationcancel="value"
//	}
func Onanimationcancel(value string) Node {
	return Attr("onanimationcancel", value)
}

// Onanimationend fires when a CSS animation finishes.
//
//	func ExampleOnanimationend() {
//		node := nodx.Onanimationend("value")
//		fmt.Println(node)
//		// Output: onanimationend="value"
//	}
func Onanimationend(value string) Node {
	return Attr("onanimationend", value)
}

// Onanimationiteration fires when a CSS animation repeats.
//
//	func ExampleOnanimationiteration() {
//		node := nodx.Onanimationiteration("value")
//		fmt.Println(node)
//		// Output: onanimationiteration="value"
//	}
func Onanimationiteration(value string) Node {
	return Attr("onanimationiteration", value)
}

// Onanimationstart fires when a CSS animation starts.
//
//	func ExampleOnanimationstart() {
//		node := nodx.Onanimationstart("value")
//		fmt.Println(node)
//		// Output: onanimationstart="value"
//	}
func Onanimationstart(value string) Node {
	return Attr("onanimationstart", value)
}

// Onauxclick fires when a non-primary mouse button is clicked.
//
//	func ExampleOnauxclick() {
//		node := nodx.Onauxclick("value")
//		fmt.Println(node)
//		// Output: onauxclick="value"
//	}
func Onauxclick(value string) Node {
	return Attr("onauxclick", value)
}

// Onbeforeinput fires when an input event is about to fire.
//
//	func ExampleOnbeforeinput() {
//		node := nodx.Onbeforeinput("value")
//		fmt.Println(node)
//		// Output: onbeforeinput="value"
//	}
func Onbeforeinput(value string) Node {
	return Attr("onbeforeinput", value)
}

// Onbeforematch fires when a hidden section is matched by the find-in-page feature.
//
//	func ExampleOnbeforematch() {
//		node := nodx.Onbeforematch("value")
//		fmt.Println(node)
//		// Output: onbeforematch="value"
//	}
func Onbeforematch(value string) Node {
	return Attr("onbeforematch", value)
}

// Onbeforetoggle fires when a popover or details element is about to toggle.
//
//	func ExampleOnbeforetoggle() {
//		node := nodx.Onbeforetoggle("value")
//		fmt.Println(node)
//		// Output: onbeforetoggle="value"
//	}
func Onbeforetoggle(value string) Node {
	return Attr("onbeforetoggle", value)
}

// Onblur fires when an element loses focus.
//
//	func ExampleOnblur() {
//		node := nodx.Onblur("value")
//		fmt.Println(node)
//		// Output: onblur="value"
//	}
func Onblur(value string) Node {
	return Attr("onblur", value)
}

// Oncancel fires when the user cancels a dialog.
//
//	func ExampleOncancel() {
//		node := nodx.Oncancel("value")
//		fmt.Println(node)
//		// Output: oncancel="value"
//	}
func Oncancel(value string) Node {
	return Attr("oncancel", value)
}

// Oncanplay fires when the media can start playing.
//
//	func ExampleOncanplay() {
//		node := nodx.Oncanplay("value")
//		fmt.Println(node)
//		// Output: oncanplay="value"
//	}
func Oncanplay(value string) Node {
	return Attr("oncanplay", value)
}

// Oncanplaythrough fires when the media can play through without buffering.
//
//	func ExampleOncanplaythrough() {
//		node := nodx.Oncanplaythrough("value")
//		fmt.Println(node)
//		// Output: oncanplaythrough="value"
//	}
func Oncanplaythrough(value string) Node {
	return Attr("oncanplaythrough", value)
}

// Onchange fires when the value of a form element changes.
//
//	func ExampleOnchange() {
//		node := nodx.Onchange("value")
//		fmt.Println(node)
//		// Output: onchange="value"
//	}
func Onchange(value string) Node {
	return Attr("onchange", value)
}

// Onclick fires when the user clicks an element.
//
//	func ExampleOnclick() {
//		node := nodx.Onclick("value")
//		fmt.Println(node)
//		// Output: onclick="value"
//	}
func Onclick(value string) Node {
	return Attr("onclick", value)
}

// Onclose fires when a dialog is closed.
//
//	func ExampleOnclose() {
//		node := nodx.Onclose("value")
//		fmt.Println(node)
//		// Output: onclose="value"
//	}
func Onclose(value string) Node {
	return Attr("onclose", value)
}

// Oncontextlost fires when a context menu cannot open.
//
//	func ExampleOncontextlost() {
//		node := nodx.Oncontextlost("value")
//		fmt.Println(node)
//		// Output: oncontextlost="value"
//	}
func Oncontextlost(value string) Node {
	return Attr("oncontextlost", value)
}

// Oncontextmenu fires when the user opens a context menu.
//
//	func ExampleOncontextmenu() {
//		node := nodx.Oncontextmenu("value")
//		fmt.Println(node)
//		// Output: oncontextmenu="value"
//	}
func Oncontextmenu(value string) Node {
	return Attr("oncontextmenu", value)
}

// Oncontextrestored fires when a context menu is restored.
//
//	func ExampleOncontextrestored() {
//		node := nodx.Oncontextrestored("value")
//		fmt.Println(node)
//		// Output: oncontextrestored="value"
//	}
func Oncontextrestored(value string) Node {
	return Attr("oncontextrestored", value)
}

// Oncopy fires when the user copies content.
//
//	func ExampleOncopy() {
//		node := nodx.Oncopy("value")
//		fmt.Println(node)
//		// Output: oncopy="value"
//	}
func Oncopy(value string) Node {
	return Attr("oncopy", value)
}

// Oncuechange fires when the current cue of a text track changes.
//
//	func ExampleOncuechange() {
//		node := nodx.Oncuechange("value")
//		fmt.Println(node)
//		// Output: oncuechange="value"
//	}
func Oncuechange(value string) Node {
	return Attr("oncuechange", value)
}

// Oncut fires when the user cuts content.
//
//	func ExampleOncut() {
//		node := nodx.Oncut("value")
//		fmt.Println(node)
//		// Output: oncut="value"
//	}
func Oncut(value string) Node {
	return Attr("oncut", value)
}

// Ondblclick fires when the user double-clicks an element.
//
//	func ExampleOndblclick() {
//		node := nodx.Ondblclick("value")
//		fmt.Println(node)
//		// Output: ondblclick="value"
//	}
func Ondblclick(value string) Node {
	return Attr("ondblclick", value)
}

// Ondrag fires when an element is being dragged.
//
//	func ExampleOndrag() {
//		node := nodx.Ondrag("value")
//		fmt.Println(node)
//		// Output: ondrag="value"
//	}
func Ondrag(value string) Node {
	return Attr("ondrag", value)
}

// Ondragend fires when a drag operation ends.
//
//	func ExampleOndragend() {
//		node := nodx.Ondragend("value")
//		fmt.Println(node)
//		// Output: ondragend="value"
//	}
func Ondragend(value string) Node {
	return Attr("ondragend", value)
}

// Ondragenter fires when a dragged element enters a drop target.
//
//	func ExampleOndragenter() {
//		node := nodx.Ondragenter("value")
//		fmt.Println(node)
//		// Output: ondragenter="value"
//	}
func Ondragenter(value string) Node {
	return Attr("ondragenter", value)
}

// Ondragleave fires when a dragged element leaves a drop target.
//
//	func ExampleOndragleave() {
//		node := nodx.Ondragleave("value")
//		fmt.Println(node)
//		// Output: ondragleave="value"
//	}
func Ondragleave(value string) Node {
	return Attr("ondragleave", value)
}

// Ondragover fires when a dragged element is over a drop target.
//
//	func ExampleOndragover() {
//		node := nodx.Ondragover("value")
//		fmt.Println(node)
//		// Output: ondragover="value"
//	}
func Ondragover(value string) Node {
	return Attr("ondragover", value)
}

// Ondragstart fires when a drag operation starts.
//
//	func ExampleOndragstart() {
//		node := nodx.Ondragstart("value")
//		fmt.Println(node)
//		// Output: ondragstart="value"
//	}
func Ondragstart(value string) Node {
	return Attr("ondragstart", value)
}

// Ondrop fires when a dragged element is dropped.
//
//	func ExampleOndrop() {
//		node := nodx.Ondrop("value")
//		fmt.Println(node)
//		// Output: ondrop="value"
//	}
func Ondrop(value string) Node {
	return Attr("ondrop", value)
}

// Ondurationchange fires when the duration of the media changes.
//
//	func ExampleOndurationchange() {
//		node := nodx.Ondurationchange("value")
//		fmt.Println(node)
//		// Output: ondurationchange="value"
//	}
func Ondurationchange(value string) Node {
	return Attr("ondurationchange", value)
}

// Onemptied fires when the media becomes empty.
//
//	func ExampleOnemptied() {
//		node := nodx.Onemptied("value")
//		fmt.Println(node)
//		// Output: onemptied="value"
//	}
func Onemptied(value string) Node {
	return Attr("onemptied", value)
}

// Onended fires when the media reaches the end.
//
//	func ExampleOnended() {
//		node := nodx.Onended("value")
//		fmt.Println(node)
//		// Output: onended="value"
//	}
func Onended(value string) Node {
	return Attr("onended", value)
}

// Onerror fires when a resource fails to load.
//
//	func ExampleOnerror() {
//		node := nodx.Onerror("value")
//		fmt.Println(node)
//		// Output: onerror="value"
//	}
func Onerror(value string) Node {
	return Attr("onerror", value)
}

// Onfocus fires when an element gains focus.
//
//	func ExampleOnfocus() {
//		node := nodx.Onfocus("value")
//		fmt.Println(node)
//		// Output: onfocus="value"
//	}
func Onfocus(value string) Node {
	return Attr("onfocus", value)
}

// Onformdata fires when the form data set is built.
//
//	func ExampleOnformdata() {
//		node := nodx.Onformdata("value")
//		fmt.Println(node)
//		// Output: onformdata="value"
//	}
func Onformdata(value string) Node {
	return Attr("onformdata", value)
}

// Ongotpointercapture fires when a pointer is captured.
//
//	func ExampleOngotpointercapture() {
//		node := nodx.Ongotpointercapture("value")
//		fmt.Println(node)
//		// Output: ongotpointercapture="value"
//	}
func Ongotpointercapture(value string) Node {
	return Attr("ongotpointercapture", value)
}

// Oninput fires when the value of an input element changes.
//
//	func ExampleOninput() {
//		node := nodx.Oninput("value")
//		fmt.Println(node)
//		// Output: oninput="value"
//	}
func Oninput(value string) Node {
	return Attr("oninput", value)
}

// Oninvalid fires when a form element fails validation.
//
//	func ExampleOninvalid() {
//		node := nodx.Oninvalid("value")
//		fmt.Println(node)
//		// Output: oninvalid="value"
//	}
func Oninvalid(value string) Node {
	return Attr("oninvalid", value)
}

// Onkeydown fires when a key is pressed down.
//
//	func ExampleOnkeydown() {
//		node := nodx.Onkeydown("value")
//		fmt.Println(node)
//		// Output: onkeydown="value"
//	}
func Onkeydown(value string) Node {
	return Attr("onkeydown", value)
}

// Onkeypress fires when a key is pressed (deprecated).
//
//	func ExampleOnkeypress() {
//		node := nodx.Onkeypress("value")
//		fmt.Println(node)
//		// Output: onkeypress="value"
//	}
func Onkeypress(value string) Node {
	return Attr("onkeypress", value)
}

// Onkeyup fires when a key is released.
//
//	func ExampleOnkeyup() {
//		node := nodx.Onkeyup("value")
//		fmt.Println(node)
//		// Output: onkeyup="value"
//	}
func Onkeyup(value string) Node {
	return Attr("onkeyup", value)
}

// Onload fires when a resource finishes loading.
//
//	func ExampleOnload() {
//		node := nodx.Onload("value")
//		fmt.Println(node)
//		// Output: onload="value"
//	}
func Onload(value string) Node {
	return Attr("onload", value)
}

// Onloadeddata fires when the first frame of the media is loaded.
//
//	func ExampleOnloadeddata() {
//		node := nodx.Onloadeddata("value")
//		fmt.Println(node)
//		// Output: onloadeddata="value"
//	}
func Onloadeddata(value string) Node {
	return Attr("onloadeddata", value)
}

// Onloadedmetadata fires when the metadata of the media is loaded.
//
//	func ExampleOnloadedmetadata() {
//		node := nodx.Onloadedmetadata("value")
//		fmt.Println(node)
//		// Output: onloadedmetadata="value"
//	}
func Onloadedmetadata(value string) Node {
	return Attr("onloadedmetadata", value)
}

// Onloadstart fires when the loading of a resource starts.
//
//	func ExampleOnloadstart() {
//		node := nodx.Onloadstart("value")
//		fmt.Println(node)
//		// Output: onloadstart="value"
//	}
func Onloadstart(value string) Node {
	return Attr("onloadstart", value)
}

// Onlostpointercapture fires when pointer capture is released.
//
//	func ExampleOnlostpointercapture() {
//		node := nodx.Onlostpointercapture("value")
//		fmt.Println(node)
//		// Output: onlostpointercapture="value"
//	}
func Onlostpointercapture(value string) Node {
	return Attr("onlostpointercapture", value)
}

// Onmousedown fires when a mouse button is pressed down.
//
//	func ExampleOnmousedown() {
//		node := nodx.Onmousedown("value")
//		fmt.Println(node)
//		// Output: onmousedown="value"
//	}
func Onmousedown(value string) Node {
	return Attr("onmousedown", value)
}

// Onmouseenter fires when the pointer enters an element.
//
//	func ExampleOnmouseenter() {
//		node := nodx.Onmouseenter("value")
//		fmt.Println(node)
//		// Output: onmouseenter="value"
//	}
func Onmouseenter(value string) Node {
	return Attr("onmouseenter", value)
}

// Onmouseleave fires when the pointer leaves an element.
//
//	func ExampleOnmouseleave() {
//		node := nodx.Onmouseleave("value")
//		fmt.Println(node)
//		// Output: onmouseleave="value"
//	}
func Onmouseleave(value string) Node {
	return Attr("onmouseleave", value)
}

// Onmousemove fires when the pointer moves over an element.
//
//	func ExampleOnmousemove() {
//		node := nodx.Onmousemove("value")
//		fmt.Println(node)
//		// Output: onmousemove="value"
//	}
func Onmousemove(value string) Node {
	return Attr("onmousemove", value)
}

// Onmouseout fires when the pointer leaves an element or one of its children.
//
//	func ExampleOnmouseout() {
//		node := nodx.Onmouseout("value")
//		fmt.Println(node)
//		// Output: onmouseout="value"
//	}
func Onmouseout(value string) Node {
	return Attr("onmouseout", value)
}

// Onmouseover fires when the pointer moves onto an element.
//
//	func ExampleOnmouseover() {
//		node := nodx.Onmouseover("value")
//		fmt.Println(node)
//		// Output: onmouseover="value"
//	}
func Onmouseover(value string) Node {
	return Attr("onmouseover", value)
}

// Onmouseup fires when a mouse button is released.
//
//	func ExampleOnmouseup() {
//		node := nodx.Onmouseup("value")
//		fmt.Println(node)
//		// Output: onmouseup="value"
//	}
func Onmouseup(value string) Node {
	return Attr("onmouseup", value)
}

// Onpaste fires when the user pastes content.
//
//	func ExampleOnpaste() {
//		node := nodx.Onpaste("value")
//		fmt.Println(node)
//		// Output: onpaste="value"
//	}
func Onpaste(value string) Node {
	return Attr("onpaste", value)
}

// Onpause fires when the media is paused.
//
//	func ExampleOnpause() {
//		node := nodx.Onpause("value")
//		fmt.Println(node)
//		// Output: onpause="value"
//	}
func Onpause(value string) Node {
	return Attr("onpause", value)
}

// Onplay fires when the media starts playing.
//
//	func ExampleOnplay() {
//		node := nodx.Onplay("value")
//		fmt.Println(node)
//		// Output: onplay="value"
//	}
func Onplay(value string) Node {
	return Attr("onplay", value)
}

// Onplaying fires when the media is playing.
//
//	func ExampleOnplaying() {
//		node := nodx.Onplaying("value")
//		fmt.Println(node)
//		// Output: onplaying="value"
//	}
func Onplaying(value string) Node {
	return Attr("onplaying", value)
}

// Onpointercancel fires when a pointer event is cancelled.
//
//	func ExampleOnpointercancel() {
//		node := nodx.Onpointercancel("value")
//		fmt.Println(node)
//		// Output: onpointercancel="value"
//	}
func Onpointercancel(value string) Node {
	return Attr("onpointercancel", value)
}

// Onpointerdown fires when a pointer is pressed down.
//
//	func ExampleOnpointerdown() {
//		node := nodx.Onpointerdown("value")
//		fmt.Println(node)
//		// Output: onpointerdown="value"
//	}
func Onpointerdown(value string) Node {
	return Attr("onpointerdown", value)
}

// Onpointerenter fires when the pointer enters the hit test area.
//
//	func ExampleOnpointerenter() {
//		node := nodx.Onpointerenter("value")
//		fmt.Println(node)
//		// Output: onpointerenter="value"
//	}
func Onpointerenter(value string) Node {
	return Attr("onpointerenter", value)
}

// Onpointerleave fires when the pointer leaves the hit test area.
//
//	func ExampleOnpointerleave() {
//		node := nodx.Onpointerleave("value")
//		fmt.Println(node)
//		// Output: onpointerleave="value"
//	}
func Onpointerleave(value string) Node {
	return Attr("onpointerleave", value)
}

// Onpointermove fires when the pointer moves.
//
//	func ExampleOnpointermove() {
//		node := nodx.Onpointermove("value")
//		fmt.Println(node)
//		// Output: onpointermove="value"
//	}
func Onpointermove(value string) Node {
	return Attr("onpointermove", value)
}

// Onpointerout fires when the pointer leaves the hit test boundaries.
//
//	func ExampleOnpointerout() {
//		node := nodx.Onpointerout("value")
//		fmt.Println(node)
//		// Output: onpointerout="value"
//	}
func Onpointerout(value string) Node {
	return Attr("onpointerout", value)
}

// Onpointerover fires when the pointer moves onto the hit test area.
//
//	func ExampleOnpointerover() {
//		node := nodx.Onpointerover("value")
//		fmt.Println(node)
//		// Output: onpointerover="value"
//	}
func Onpointerover(value string) Node {
	return Attr("onpointerover", value)
}

// Onpointerup fires when the pointer is released.
//
//	func ExampleOnpointerup() {
//		node := nodx.Onpointerup("value")
//		fmt.Println(node)
//		// Output: onpointerup="value"
//	}
func Onpointerup(value string) Node {
	return Attr("onpointerup", value)
}

// Onprogress fires while the media is loading.
//
//	func ExampleOnprogress() {
//		node := nodx.Onprogress("value")
//		fmt.Println(node)
//		// Output: onprogress="value"
//	}
func Onprogress(value string) Node {
	return Attr("onprogress", value)
}

// Onratechange fires when the playback rate changes.
//
//	func ExampleOnratechange() {
//		node := nodx.Onratechange("value")
//		fmt.Println(node)
//		// Output: onratechange="value"
//	}
func Onratechange(value string) Node {
	return Attr("onratechange", value)
}

// Onreset fires when a form is reset.
//
//	func ExampleOnreset() {
//		node := nodx.Onreset("value")
//		fmt.Println(node)
//		// Output: onreset="value"
//	}
func Onreset(value string) Node {
	return Attr("onreset", value)
}

// Onresize fires when the document view is resized.
//
//	func ExampleOnresize() {
//		node := nodx.Onresize("value")
//		fmt.Println(node)
//		// Output: onresize="value"
//	}
func Onresize(value string) Node {
	return Attr("onresize", value)
}

// Onscroll fires when the document or an element is scrolled.
//
//	func ExampleOnscroll() {
//		node := nodx.Onscroll("value")
//		fmt.Println(node)
//		// Output: onscroll="value"
//	}
func Onscroll(value string) Node {
	return Attr("onscroll", value)
}

// Onscrollend fires when scrolling ends.
//
//	func ExampleOnscrollend() {
//		node := nodx.Onscrollend("value")
//		fmt.Println(node)
//		// Output: onscrollend="value"
//	}
func Onscrollend(value string) Node {
	return Attr("onscrollend", value)
}

// Onsecuritypolicyviolation fires when a Content Security Policy is violated.
//
//	func ExampleOnsecuritypolicyviolation() {
//		node := nodx.Onsecuritypolicyviolation("value")
//		fmt.Println(node)
//		// Output: onsecuritypolicyviolation="value"
//	}
func Onsecuritypolicyviolation(value string) Node {
	return Attr("onsecuritypolicyviolation", value)
}

// Onseeked fires when a seek operation finishes.
//
//	func ExampleOnseeked() {
//		node := nodx.Onseeked("value")
//		fmt.Println(node)
//		// Output: onseeked="value"
//	}
func Onseeked(value string) Node {
	return Attr("onseeked", value)
}

// Onseeking fires when a seek operation starts.
//
//	func ExampleOnseeking() {
//		node := nodx.Onseeking("value")
//		fmt.Println(node)
//		// Output: onseeking="value"
//	}
func Onseeking(value string) Node {
	return Attr("onseeking", value)
}

// Onselect fires when text is selected.
//
//	func ExampleOnselect() {
//		node := nodx.Onselect("value")
//		fmt.Println(node)
//		// Output: onselect="value"
//	}
func Onselect(value string) Node {
	return Attr("onselect", value)
}

// Onslotchange fires when the assigned nodes of a slot change.
//
//	func ExampleOnslotchange() {
//		node := nodx.Onslotchange("value")
//		fmt.Println(node)
//		// Output: onslotchange="value"
//	}
func Onslotchange(value string) Node {
	return Attr("onslotchange", value)
}

// Onstalled fires when the media is stalled.
//
//	func ExampleOnstalled() {
//		node := nodx.Onstalled("value")
//		fmt.Println(node)
//		// Output: onstalled="value"
//	}
func Onstalled(value string) Node {
	return Attr("onstalled", value)
}

// Onsubmit fires when a form is submitted.
//
//	func ExampleOnsubmit() {
//		node := nodx.Onsubmit("value")
//		fmt.Println(node)
//		// Output: onsubmit="value"
//	}
func Onsubmit(value string) Node {
	return Attr("onsubmit", value)
}

// Onsuspend fires when the media is suspended.
//
//	func ExampleOnsuspend() {
//		node := nodx.Onsuspend("value")
//		fmt.Println(node)
//		// Output: onsuspend="value"
//	}
func Onsuspend(value string) Node {
	return Attr("onsuspend", value)
}

// Ontimeupdate fires when the playback position changes.
//
//	func ExampleOntimeupdate() {
//		node := nodx.Ontimeupdate("value")
//		fmt.Println(node)
//		// Output: ontimeupdate="value"
//	}
func Ontimeupdate(value string) Node {
	return Attr("ontimeupdate", value)
}

// Ontoggle fires when a details or popover element toggles.
//
//	func ExampleOntoggle() {
//		node := nodx.Ontoggle("value")
//		fmt.Println(node)
//		// Output: ontoggle="value"
//	}
func Ontoggle(value string) Node {
	return Attr("ontoggle", value)
}

// Ontransitioncancel fires when a CSS transition is cancelled.
//
//	func ExampleOntransitioncancel() {
//		node := nodx.Ontransitioncancel("value")
//		fmt.Println(node)
//		// Output: ontransitioncancel="value"
//	}
func Ontransitioncancel(value string) Node {
	return Attr("ontransitioncancel", value)
}

// Ontransitionend fires when a CSS transition finishes.
//
//	func ExampleOntransitionend() {
//		node := nodx.Ontransitionend("value")
//		fmt.Println(node)
//		// Output: ontransitionend="value"
//	}
func Ontransitionend(value string) Node {
	return Attr("ontransitionend", value)
}

// Ontransitionrun fires when a CSS transition starts running.
//
//	func ExampleOntransitionrun() {
//		node := nodx.Ontransitionrun("value")
//		fmt.Println(node)
//		// Output: ontransitionrun="value"
//	}
func Ontransitionrun(value string) Node {
	return Attr("ontransitionrun", value)
}

// Ontransitionstart fires when a CSS transition starts.
//
//	func ExampleOntransitionstart() {
//		node := nodx.Ontransitionstart("value")
//		fmt.Println(node)
//		// Output: ontransitionstart="value"
//	}
func Ontransitionstart(value string) Node {
	return Attr("ontransitionstart", value)
}

// Onvolumechange fires when the media volume changes.
//
//	func ExampleOnvolumechange() {
//		node := nodx.Onvolumechange("value")
//		fmt.Println(node)
//		// Output: onvolumechange="value"
//	}
func Onvolumechange(value string) Node {
	return Attr("onvolumechange", value)
}

// Onwaiting fires when the media is waiting for data.
//
//	func ExampleOnwaiting() {
//		node := nodx.Onwaiting("value")
//		fmt.Println(node)
//		// Output: onwaiting="value"
//	}
func Onwaiting(value string) Node {
	return Attr("onwaiting", value)
}

// Onwheel fires when the mouse wheel is rotated.
//
//	func ExampleOnwheel() {
//		node := nodx.Onwheel("value")
//		fmt.Println(node)
//		// Output: onwheel="value"
//	}
func Onwheel(value string) Node {
	return Attr("onwheel", value)
}

// Open specifies that the details should be visible to the user.
//
//	func ExampleOpen() {
//		node := nodx.Open("value")
//		fmt.Println(node)
//		// Output: open="value"
//	}
func Open(value string) Node {
	return Attr("open", value)
}

// Optimum specifies the optimal value of the gauge.
//
//	func ExampleOptimum() {
//		node := nodx.Optimum("value")
//		fmt.Println(node)
//		// Output: optimum="value"
//	}
func Optimum(value string) Node {
	return Attr("optimum", value)
}

// Part identifies the element as a part of a shadow DOM.
//
//	func ExamplePart() {
//		node := nodx.Part("value")
//		fmt.Println(node)
//		// Output: part="value"
//	}
func Part(value string) Node {
	return Attr("part", value)
}

// Pattern specifies a regular expression that the input element's value is checked against.
//
//	func ExamplePattern() {
//		node := nodx.Pattern("value")
//		fmt.Println(node)
//		// Output: pattern="value"
//	}
func Pattern(value string) Node {
	return Attr("pattern", value)
}

// Ping specifies a space-separated list of URLs to be notified if a user follows the hyperlink.
//
//	func ExamplePing() {
//		node := nodx.Ping("value")
//		fmt.Println(node)
//		// Output: ping="value"
//	}
func Ping(value string) Node {
	return Attr("ping", value)
}

// Placeholder specifies a short hint that describes the expected value of an input field.
//
//	func ExamplePlaceholder() {
//		node := nodx.Placeholder("value")
//		fmt.Println(node)
//		// Output: placeholder="value"
//	}
func Placeholder(value string) Node {
	return Attr("placeholder", value)
}

// Playsinline indicates that the video should play inline on mobile devices.
//
//	func ExamplePlaysinline() {
//		node := nodx.Playsinline("value")
//		fmt.Println(node)
//		// Output: playsinline="value"
//	}
func Playsinline(value string) Node {
	return Attr("playsinline", value)
}

// Popover marks an element as a popover.
//
//	func ExamplePopover() {
//		node := nodx.Popover("value")
//		fmt.Println(node)
//		// Output: popover="value"
//	}
func Popover(value string) Node {
	return Attr("popover", value)
}

// Popovertarget specifies the id of the popover element to toggle.
//
//	func ExamplePopovertarget() {
//		node := nodx.Popovertarget("value")
//		fmt.Println(node)
//		// Output: popovertarget="value"
//	}
func Popovertarget(value string) Node {
	return Attr("popovertarget", value)
}

// Popovertargetaction specifies the action to perform on the popover target.
//
//	func ExamplePopovertargetaction() {
//		node := nodx.Popovertargetaction("value")
//		fmt.Println(node)
//		// Output: popovertargetaction="value"
//	}
func Popovertargetaction(value string) Node {
	return Attr("popovertargetaction", value)
}

// Poster specifies an image to be shown while the video is downloading or until the user hits the play button.
//
//	func ExamplePoster() {
//		node := nodx.Poster("value")
//		fmt.Println(node)
//		// Output: poster="value"
//	}
func Poster(value string) Node {
	return Attr("poster", value)
}

// Preload specifies if and how the author thinks the audio/video should be loaded when the page loads.
//
//	func ExamplePreload() {
//		node := nodx.Preload("value")
//		fmt.Println(node)
//		// Output: preload="value"
//	}
func Preload(value string) Node {
	return Attr("preload", value)
}

// Radiogroup specifies the group of radio buttons a command belongs to (deprecated).
//
//	func ExampleRadiogroup() {
//		node := nodx.Radiogroup("value")
//		fmt.Println(node)
//		// Output: radiogroup="value"
//	}
func Radiogroup(value string) Node {
	return Attr("radiogroup", value)
}

// Readonly specifies that the input field is read-only.
//
//	func ExampleReadonly() {
//		node := nodx.Readonly("value")
//		fmt.Println(node)
//		// Output: readonly="value"
//	}
func Readonly(value string) Node {
	return Attr("readonly", value)
}

// Referrerpolicy specifies which referrer information to send when fetching a resource.
//
//	func ExampleReferrerpolicy() {
//		node := nodx.Referrerpolicy("value")
//		fmt.Println(node)
//		// Output: referrerpolicy="value"
//	}
func Referrerpolicy(value string) Node {
	return Attr("referrerpolicy", value)
}

// Rel specifies the relationship between the current document and the linked document.
//
//	func ExampleRel() {
//		node := nodx.Rel("value")
//		fmt.Println(node)
//		// Output: rel="value"
//	}
func Rel(value string) Node {
	return Attr("rel", value)
}

// Required specifies that the input field must be filled out before submitting the form.
//
//	func ExampleRequired() {
//		node := nodx.Required("value")
//		fmt.Println(node)
//		// Output: required="value"
//	}
func Required(value string) Node {
	return Attr("required", value)
}

// Results specifies the maximum number of results to show in a search input (deprecated).
//
//	func ExampleResults() {
//		node := nodx.Results("value")
//		fmt.Println(node)
//		// Output: results="value"
//	}
func Results(value string) Node {
	return Attr("results", value)
}

// Reversed specifies that the list order should be descending (9,8,7...).
//
//	func ExampleReversed() {
//		node := nodx.Reversed("value")
//		fmt.Println(node)
//		// Output: reversed="value"
//	}
func Reversed(value string) Node {
	return Attr("reversed", value)
}

// Role defines the role of an element for accessibility purposes.
//
//	func ExampleRole() {
//		node := nodx.Role("value")
//		fmt.Println(node)
//		// Output: role="value"
//	}
func Role(value string) Node {
	return Attr("role", value)
}

// Rows specifies the visible number of lines in a text area.
//
//	func ExampleRows() {
//		node := nodx.Rows("value")
//		fmt.Println(node)
//		// Output: rows="value"
//	}
func Rows(value string) Node {
	return Attr("rows", value)
}

// Rowspan specifies the number of rows a cell should span.
//
//	func ExampleRowspan() {
//		node := nodx.Rowspan("value")
//		fmt.Println(node)
//		// Output: rowspan="value"
//	}
func Rowspan(value string) Node {
	return Attr("rowspan", value)
}

// Rules specifies which rules to display between table cells (deprecated).
//
//	func ExampleRules() {
//		node := nodx.Rules("value")
//		fmt.Println(node)
//		// Output: rules="value"
//	}
func Rules(value string) Node {
	return Attr("rules", value)
}

// Sandbox enables an extra set of restrictions for the content in an iframe.
//
//	func ExampleSandbox() {
//		node := nodx.Sandbox("value")
//		fmt.Println(node)
//		// Output: sandbox="value"
//	}
func Sandbox(value string) Node {
	return Attr("sandbox", value)
}

// Scope specifies whether a header cell is a header for a column, row, or group of columns or rows.
//
//	func ExampleScope() {
//		node := nodx.Scope("value")
//		fmt.Println(node)
//		// Output: scope="value"
//	}
func Scope(value string) Node {
	return Attr("scope", value)
}

// Scoped specifies that the styles only apply to this element's parent and child elements.
//
//	func ExampleScoped() {
//		node := nodx.Scoped("value")
//		fmt.Println(node)
//		// Output: scoped="value"
//	}
func Scoped(value string) Node {
	return Attr("scoped", value)
}

// Scrolling specifies whether to display scrollbars in an iframe (deprecated).
//
//	func ExampleScrolling() {
//		node := nodx.Scrolling("value")
//		fmt.Println(node)
//		// Output: scrolling="value"
//	}
func Scrolling(value string) Node {
	return Attr("scrolling", value)
}

// Selected specifies that an option should be pre-selected when the page loads.
//
//	func ExampleSelected() {
//		node := nodx.Selected("value")
//		fmt.Println(node)
//		// Output: selected="value"
//	}
func Selected(value string) Node {
	return Attr("selected", value)
}

// Shape specifies the shape of an area in an image-map.
//
//	func ExampleShape() {
//		node := nodx.Shape("value")
//		fmt.Println(node)
//		// Output: shape="value"
//	}
func Shape(value string) Node {
	return Attr("shape", value)
}

// Size specifies the width, in characters, of an input field.
//
//	func ExampleSize() {
//		node := nodx.Size("value")
//		fmt.Println(node)
//		// Output: size="value"
//	}
func Size(value string) Node {
	return Attr("size", value)
}

// Sizes specifies the sizes of icons for visual media.
//
//	func ExampleSizes() {
//		node := nodx.Sizes("value")
//		fmt.Println(node)
//		// Output: sizes="value"
//	}
func Sizes(value string) Node {
	return Attr("sizes", value)
}

// SlotAttr assigns a slot in a shadow DOM shadow tree.
//
//	func ExampleSlotAttr() {
//		node := nodx.SlotAttr("value")
//		fmt.Println(node)
//		// Output: slot="value"
//	}
func SlotAttr(value string) Node {
	return Attr("slot", value)
}

// SpanAttr defines the number of columns to span for a col or colgroup element.
//
//	func ExampleSpanAttr() {
//		node := nodx.SpanAttr("value")
//		fmt.Println(node)
//		// Output: span="value"
//	}
func SpanAttr(value string) Node {
	return Attr("span", value)
}

// Spellcheck specifies whether the element is to have its spelling and grammar checked or not.
//
//	func ExampleSpellcheck() {
//		node := nodx.Spellcheck("value")
//		fmt.Println(node)
//		// Output: spellcheck="value"
//	}
func Spellcheck(value string) Node {
	return Attr("spellcheck", value)
}

// Src specifies the URL of the media file.
//
//	func ExampleSrc() {
//		node := nodx.Src("value")
//		fmt.Println(node)
//		// Output: src="value"
//	}
func Src(value string) Node {
	return Attr("src", value)
}

// Srcdoc specifies the HTML content of the page to show in the iframe.
//
//	func ExampleSrcdoc() {
//		node := nodx.Srcdoc("value")
//		fmt.Println(node)
//		// Output: srcdoc="value"
//	}
func Srcdoc(value string) Node {
	return Attr("srcdoc", value)
}

// Srclang specifies the language of the track text data (required if kind='subtitles').
//
//	func ExampleSrclang() {
//		node := nodx.Srclang("value")
//		fmt.Println(node)
//		// Output: srclang="value"
//	}
func Srclang(value string) Node {
	return Attr("srclang", value)
}

// Srcset specifies the URL of the image to use in different situations.
//
//	func ExampleSrcset() {
//		node := nodx.Srcset("value")
//		fmt.Println(node)
//		// Output: srcset="value"
//	}
func Srcset(value string) Node {
	return Attr("srcset", value)
}

// Standby specifies a message to show while an object loads (deprecated).
//
//	func ExampleStandby() {
//		node := nodx.Standby("value")
//		fmt.Println(node)
//		// Output: standby="value"
//	}
func Standby(value string) Node {
	return Attr("standby", value)
}

// Start specifies the start value of an ordered list.
//
//	func ExampleStart() {
//		node := nodx.Start("value")
//		fmt.Println(node)
//		// Output: start="value"
//	}
func Start(value string) Node {
	return Attr("start", value)
}

// Step specifies the legal number intervals for an input field.
//
//	func ExampleStep() {
//		node := nodx.Step("value")
//		fmt.Println(node)
//		// Output: step="value"
//	}
func Step(value string) Node {
	return Attr("step", value)
}

// StyleAttr specifies an inline CSS style for an element.
//
//	func ExampleStyleAttr() {
//		node := nodx.StyleAttr("value")
//		fmt.Println(node)
//		// Output: style="value"
//	}
func StyleAttr(value string) Node {
	return Attr("style", value)
}

// SummaryAttr specifies a summary of the content of a table (deprecated in HTML5).
//
//	func ExampleSummaryAttr() {
//		node := nodx.SummaryAttr("value")
//		fmt.Println(node)
//		// Output: summary="value"
//	}
func SummaryAttr(value string) Node {
	return Attr("summary", value)
}

// Tabindex specifies the tabbing order of an element.
//
//	func ExampleTabindex() {
//		node := nodx.Tabindex("value")
//		fmt.Println(node)
//		// Output: tabindex="value"
//	}
func Tabindex(value string) Node {
	return Attr("tabindex", value)
}

// Target specifies where to open the linked document.
//
//	func ExampleTarget() {
//		node := nodx.Target("value")
//		fmt.Println(node)
//		// Output: target="value"
//	}
func Target(value string) Node {
	return Attr("target", value)
}

// TitleAttr specifies extra information about an element.
//
//	func ExampleTitleAttr() {
//		node := nodx.TitleAttr("value")
//		fmt.Println(node)
//		// Output: title="value"
//	}
func TitleAttr(value string) Node {
	return Attr("title", value)
}

// Translate specifies whether the content of an element should be translated or not.
//
//	func ExampleTranslate() {
//		node := nodx.Translate("value")
//		fmt.Println(node)
//		// Output: translate="value"
//	}
func Translate(value string) Node {
	return Attr("translate", value)
}

// Type specifies the type of element.
//
//	func ExampleType() {
//		node := nodx.Type("value")
//		fmt.Println(node)
//		// Output: type="value"
//	}
func Type(value string) Node {
	return Attr("type", value)
}

// Usemap specifies an image as a client-side image-map.
//
//	func ExampleUsemap() {
//		node := nodx.Usemap("value")
//		fmt.Println(node)
//		// Output: usemap="value"
//	}
func Usemap(value string) Node {
	return Attr("usemap", value)
}

// Valign specifies the vertical alignment of the content (deprecated).
//
//	func ExampleValign() {
//		node := nodx.Valign("value")
//		fmt.Println(node)
//		// Output: valign="value"
//	}
func Valign(value string) Node {
	return Attr("valign", value)
}

// Value specifies the value of the element.
//
//	func ExampleValue() {
//		node := nodx.Value("value")
//		fmt.Println(node)
//		// Output: value="value"
//	}
func Value(value string) Node {
	return Attr("value", value)
}

// Valuetype specifies the type of the value of a param element (deprecated).
//
//	func ExampleValuetype() {
//		node := nodx.Valuetype("value")
//		fmt.Println(node)
//		// Output: valuetype="value"
//	}
func Valuetype(value string) Node {
	return Attr("valuetype", value)
}

// Vspace specifies the vertical space around an element (deprecated).
//
//	func ExampleVspace() {
//		node := nodx.Vspace("value")
//		fmt.Println(node)
//		// Output: vspace="value"
//	}
func Vspace(value string) Node {
	return Attr("vspace", value)
}

// Width specifies the width of the element.
//
//	func ExampleWidth() {
//		node := nodx.Width("value")
//		fmt.Println(node)
//		// Output: width="value"
//	}
func Width(value string) Node {
	return Attr("width", value)
}

// Wrap specifies how the text in a text area is to be wrapped when submitted in a form.
//
//	func ExampleWrap() {
//		node := nodx.Wrap("value")
//		fmt.Println(node)
//		// Output: wrap="value"
//	}
func Wrap(value string) Node {
	return Attr("wrap", value)
}
